// Code generated by cmd/handlergen. DO NOT EDIT.

package schedule

import (
	"edu-schedule-system/internal/pkg/core"
)

func RegisterGeneratedScheduleRoutes(h *Handler, r core.RouterGroup) {
	// 新增数据
	r.POST("/schedule", h.Create())

	// 获取列表数据
	r.GET("/schedules", h.List())

	// 根据 ID 获取数据
	r.GET("/schedule/:id", h.GetByID())

	// 根据 ID 更新数据
	r.PUT("/schedule/:id", h.UpdateByID())

	// 根据 ID 删除数据
	r.DELETE("/schedule/:id", h.DeleteByID())
}
