// Code generated by cmd/handlergen. DO NOT EDIT.

package schedule

import (
	"errors"
	"net/http"
	"strconv"
	"strings"

	"edu-schedule-system/internal/api/apierr"
	"edu-schedule-system/internal/code"
	"edu-schedule-system/internal/pkg/core"
	"edu-schedule-system/internal/proposal"
	"edu-schedule-system/internal/service"
	"edu-schedule-system/internal/service/apperr"
	"edu-schedule-system/internal/service/dto"
	"edu-schedule-system/internal/service/schedule"

	mysqlDriver "github.com/go-sql-driver/mysql"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

type Handler struct {
	logger          *zap.Logger
	scheduleService schedule.Service
}

type genResultInfo struct {
	RowsAffected int64 `json:"rows_affected"`
}

func New(logger *zap.Logger, scheduleService schedule.Service) *Handler {
	return &Handler{
		logger:          logger,
		scheduleService: scheduleService,
	}
}

func (h *Handler) abortServiceError(ctx core.Context, err error) {
	var appErr *apperr.Error
	if errors.As(err, &appErr) {
		switch appErr.Kind {
		case apperr.KindInvalidArgument:
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				appErr.Message),
			)
		case apperr.KindNotFound:
			ctx.AbortWithError(core.Error(
				http.StatusNotFound,
				code.RecordNotFound,
				appErr.Message),
			)
		case apperr.KindConflict:
			ctx.AbortWithError(core.Error(
				http.StatusConflict,
				code.Conflict,
				appErr.Message),
			)
		case apperr.KindForbidden:
			ctx.AbortWithError(core.Error(
				http.StatusForbidden,
				code.Forbidden,
				appErr.Message),
			)
		case apperr.KindDependencyFailed:
			ctx.AbortWithError(core.Error(
				http.StatusServiceUnavailable,
				code.DependencyFailed,
				appErr.Message),
			)
		default:
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				appErr.Message),
			)
		}
		return
	}

	var mysqlErr *mysqlDriver.MySQLError
	if errors.As(err, &mysqlErr) {
		if mysqlErr.Number == 1062 || mysqlErr.Number == 1451 || mysqlErr.Number == 1452 || mysqlErr.Number == 3819 || mysqlErr.Number == 3822 {
			ctx.AbortWithError(core.Error(
				http.StatusConflict,
				code.Conflict,
				databaseConflictMessage(mysqlErr.Message)),
			)
			return
		}
	}

	ctx.AbortWithError(core.Error(
		http.StatusInternalServerError,
		code.ServerError,
		code.Text(code.ServerError)),
	)
}

func databaseConflictMessage(message string) string {
	message = strings.TrimSpace(message)
	if message == "" {
		return code.Text(code.Conflict)
	}
	if strings.Contains(strings.ToLower(message), "uk_schedule_teacher_exact_slot") {
		return "当前时间段存在排课冲突 [teacher=true student=false]"
	}
	if strings.Contains(strings.ToLower(message), "uk_schedule_student_exact_slot") {
		return "当前时间段存在排课冲突 [teacher=false student=true]"
	}
	return apierr.TranslateMySQLConstraintMessage(message)
}

func abortBadID(ctx core.Context) {
	ctx.AbortWithError(core.Error(
		http.StatusBadRequest,
		code.ParamBindError,
		"id must be a positive integer"),
	)
}

// Create 新增数据
// @Summary 新增数据
// @Description 新增数据
// @Tags Table.schedule
// @Accept json
// @Produce json
// @Param RequestBody body dto.ScheduleCreateRequest true "请求参数"
// @Success 200 {object} map[string]interface{}
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/schedule [post]
func (h *Handler) Create() core.HandlerFunc {
	return func(ctx core.Context) {
		var req dto.ScheduleCreateRequest
		if err := ctx.ShouldBindJSON(&req); err != nil {
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				err.Error()),
			)
			return
		}

		if err := service.EnsureDataScopeStudentOrTeacher(ctx.SessionUserInfo(), req.StudentID, req.TeacherID); err != nil {
			h.abortServiceError(ctx, err)
			return
		}

		id, err := h.scheduleService.Create(ctx.RequestContext(), &req)
		if err != nil {
			h.abortServiceError(ctx, err)
			return
		}

		ctx.Payload(map[string]interface{}{"id": id})
	}
}

// List 获取列表数据
// @Summary 获取列表数据
// @Description 获取列表数据
// @Tags Table.schedule
// @Accept json
// @Produce json
// @Success 200 {object} []dto.ScheduleResponse
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/schedules [get]
func (h *Handler) List() core.HandlerFunc {
	return func(ctx core.Context) {
		query := dto.ScheduleListQuery{}
		if err := ctx.ShouldBindQuery(&query); err != nil {
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				err.Error()),
			)
			return
		}

		if ctx.SessionUserInfo().DataScope == proposal.DataScopeSelf {
			query.TeacherID = ctx.SessionUserInfo().Id
		}

		list, err := h.scheduleService.List(ctx.RequestContext(), query)
		if err != nil {
			h.abortServiceError(ctx, err)
			return
		}

		ctx.Payload(list)
	}
}

// GetByID 根据 ID 获取数据
// @Summary 根据 ID 获取数据
// @Description 根据 ID 获取数据
// @Tags Table.schedule
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} dto.ScheduleResponse
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/schedule/{id} [get]
func (h *Handler) GetByID() core.HandlerFunc {
	return func(ctx core.Context) {
		id, err := strconv.Atoi(ctx.Param("id"))
		if err != nil || id <= 0 {
			abortBadID(ctx)
			return
		}

		info, err := h.scheduleService.GetByID(ctx.RequestContext(), int32(id))
		if err == nil {
			if scopeErr := service.EnsureDataScopeStudentOrTeacher(ctx.SessionUserInfo(), info.StudentID, info.TeacherID); scopeErr != nil {
				h.abortServiceError(ctx, scopeErr)
				return
			}
		}
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				ctx.AbortWithError(core.Error(
					http.StatusNotFound,
					code.RecordNotFound,
					"record not found"),
				)
			} else {
				h.abortServiceError(ctx, err)
			}
			return
		}

		ctx.Payload(info)
	}
}

// DeleteByID 根据 ID 删除数据
// @Summary 根据 ID 删除数据
// @Description 根据 ID 删除数据
// @Tags Table.schedule
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} genResultInfo
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/schedule/{id} [delete]
func (h *Handler) DeleteByID() core.HandlerFunc {
	return func(ctx core.Context) {
		id, err := strconv.Atoi(ctx.Param("id"))
		if err != nil || id <= 0 {
			abortBadID(ctx)
			return
		}

		existing, lookupErr := h.scheduleService.GetByID(ctx.RequestContext(), int32(id))
		if lookupErr != nil {
			h.abortServiceError(ctx, lookupErr)
			return
		}
		if err := service.EnsureDataScopeStudentOrTeacher(ctx.SessionUserInfo(), existing.StudentID, existing.TeacherID); err != nil {
			h.abortServiceError(ctx, err)
			return
		}

		rowsAffected, err := h.scheduleService.DeleteByID(ctx.RequestContext(), int32(id))
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				ctx.AbortWithError(core.Error(
					http.StatusNotFound,
					code.RecordNotFound,
					"record not found"),
				)
			} else {
				h.abortServiceError(ctx, err)
			}
			return
		}

		resultInfo := new(genResultInfo)
		resultInfo.RowsAffected = rowsAffected

		ctx.Payload(resultInfo)
	}
}

// UpdateByID 根据 ID 更新数据
// @Summary 根据 ID 更新数据
// @Description 根据 ID 更新数据
// @Tags Table.schedule
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Param RequestBody body dto.ScheduleUpdateRequest true "请求参数"
// @Success 200 {object} genResultInfo
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/schedule/{id} [put]
func (h *Handler) UpdateByID() core.HandlerFunc {
	return func(ctx core.Context) {
		id, err := strconv.Atoi(ctx.Param("id"))
		if err != nil || id <= 0 {
			abortBadID(ctx)
			return
		}

		var updateData dto.ScheduleUpdateRequest
		if err := ctx.ShouldBindJSON(&updateData); err != nil {
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				err.Error()),
			)
			return
		}

		rowsAffected, err := h.scheduleService.UpdateByID(ctx.RequestContext(), int32(id), updateData)
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				ctx.AbortWithError(core.Error(
					http.StatusNotFound,
					code.RecordNotFound,
					"record not found"),
				)
			} else {
				h.abortServiceError(ctx, err)
			}
			return
		}

		resultInfo := new(genResultInfo)
		resultInfo.RowsAffected = rowsAffected

		ctx.Payload(resultInfo)
	}
}
