// Code generated by cmd/handlergen. DO NOT EDIT.

package lesson_record

import (
	"errors"
	"net/http"
	"strconv"

	"edu-schedule-system/internal/code"
	"edu-schedule-system/internal/pkg/core"
	"edu-schedule-system/internal/service"
	"edu-schedule-system/internal/service/apperr"
	"edu-schedule-system/internal/service/dto"
	"edu-schedule-system/internal/service/lesson_record"

	"go.uber.org/zap"
	"gorm.io/gorm"
)

type Handler struct {
	logger               *zap.Logger
	lesson_recordService lesson_record.Service
}

type genResultInfo struct {
	RowsAffected int64 `json:"rows_affected"`
}

func New(logger *zap.Logger, lesson_recordService lesson_record.Service) *Handler {
	return &Handler{
		logger:               logger,
		lesson_recordService: lesson_recordService,
	}
}

func (h *Handler) abortServiceError(ctx core.Context, err error) {
	var appErr *apperr.Error
	if errors.As(err, &appErr) {
		switch appErr.Kind {
		case apperr.KindInvalidArgument:
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				appErr.Message),
			)
		case apperr.KindNotFound:
			ctx.AbortWithError(core.Error(
				http.StatusNotFound,
				code.RecordNotFound,
				appErr.Message),
			)
		case apperr.KindConflict:
			ctx.AbortWithError(core.Error(
				http.StatusConflict,
				code.Conflict,
				appErr.Message),
			)
		case apperr.KindForbidden:
			ctx.AbortWithError(core.Error(
				http.StatusForbidden,
				code.Forbidden,
				appErr.Message),
			)
		case apperr.KindDependencyFailed:
			ctx.AbortWithError(core.Error(
				http.StatusServiceUnavailable,
				code.DependencyFailed,
				appErr.Message),
			)
		default:
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				appErr.Message),
			)
		}
		return
	}

	ctx.AbortWithError(core.Error(
		http.StatusInternalServerError,
		code.ServerError,
		code.Text(code.ServerError)),
	)
}

func abortBadID(ctx core.Context) {
	ctx.AbortWithError(core.Error(
		http.StatusBadRequest,
		code.ParamBindError,
		"id must be a positive integer"),
	)
}

// Create 新增数据
// @Summary 新增数据
// @Description 新增数据
// @Tags Table.lesson_record
// @Accept json
// @Produce json
// @Param RequestBody body dto.LessonRecordCreateRequest true "请求参数"
// @Success 200 {object} map[string]interface{}
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/lesson_record [post]
func (h *Handler) Create() core.HandlerFunc {
	return func(ctx core.Context) {
		var req dto.LessonRecordCreateRequest
		if err := ctx.ShouldBindJSON(&req); err != nil {
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				err.Error()),
			)
			return
		}

		id, err := h.lesson_recordService.Create(ctx.RequestContext(), &req)
		if err != nil {
			h.abortServiceError(ctx, err)
			return
		}

		ctx.Payload(map[string]interface{}{"id": id})
	}
}

// List 获取列表数据
// @Summary 获取列表数据
// @Description 获取列表数据
// @Tags Table.lesson_record
// @Accept json
// @Produce json
// @Success 200 {object} []dto.LessonRecordResponse
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/lesson_records [get]
func (h *Handler) List() core.HandlerFunc {
	return func(ctx core.Context) {
		list, err := h.lesson_recordService.List(ctx.RequestContext())
		if err != nil {
			h.abortServiceError(ctx, err)
			return
		}

		ctx.Payload(list)
	}
}

// GetByID 根据 ID 获取数据
// @Summary 根据 ID 获取数据
// @Description 根据 ID 获取数据
// @Tags Table.lesson_record
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} dto.LessonRecordResponse
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/lesson_record/{id} [get]
func (h *Handler) GetByID() core.HandlerFunc {
	return func(ctx core.Context) {
		id, err := strconv.Atoi(ctx.Param("id"))
		if err != nil || id <= 0 {
			abortBadID(ctx)
			return
		}

		info, err := h.lesson_recordService.GetByID(ctx.RequestContext(), int32(id))
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				ctx.AbortWithError(core.Error(
					http.StatusNotFound,
					code.RecordNotFound,
					"record not found"),
				)
			} else {
				h.abortServiceError(ctx, err)
			}
			return
		}

		ctx.Payload(info)
	}
}

// DeleteByID 根据 ID 删除数据
// @Summary 根据 ID 删除数据
// @Description 根据 ID 删除数据
// @Tags Table.lesson_record
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} genResultInfo
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/lesson_record/{id} [delete]
func (h *Handler) DeleteByID() core.HandlerFunc {
	return func(ctx core.Context) {
		id, err := strconv.Atoi(ctx.Param("id"))
		if err != nil || id <= 0 {
			abortBadID(ctx)
			return
		}

		existing, lookupErr := h.lesson_recordService.GetByID(ctx.RequestContext(), int32(id))
		if lookupErr != nil {
			h.abortServiceError(ctx, lookupErr)
			return
		}
		if err := service.EnsureDataScopeStudentOrTeacher(ctx.SessionUserInfo(), existing.StudentID, existing.TeacherID); err != nil {
			h.abortServiceError(ctx, err)
			return
		}

		rowsAffected, err := h.lesson_recordService.DeleteByID(ctx.RequestContext(), int32(id))
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				ctx.AbortWithError(core.Error(
					http.StatusNotFound,
					code.RecordNotFound,
					"record not found"),
				)
			} else {
				h.abortServiceError(ctx, err)
			}
			return
		}

		resultInfo := new(genResultInfo)
		resultInfo.RowsAffected = rowsAffected

		ctx.Payload(resultInfo)
	}
}

// UpdateByID 根据 ID 更新数据
// @Summary 根据 ID 更新数据
// @Description 根据 ID 更新数据
// @Tags Table.lesson_record
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Param RequestBody body dto.LessonRecordUpdateRequest true "请求参数"
// @Success 200 {object} genResultInfo
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/lesson_record/{id} [put]
func (h *Handler) UpdateByID() core.HandlerFunc {
	return func(ctx core.Context) {
		id, err := strconv.Atoi(ctx.Param("id"))
		if err != nil || id <= 0 {
			abortBadID(ctx)
			return
		}

		var updateData dto.LessonRecordUpdateRequest
		if err := ctx.ShouldBindJSON(&updateData); err != nil {
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				err.Error()),
			)
			return
		}

		rowsAffected, err := h.lesson_recordService.UpdateByID(ctx.RequestContext(), int32(id), updateData)
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				ctx.AbortWithError(core.Error(
					http.StatusNotFound,
					code.RecordNotFound,
					"record not found"),
				)
			} else {
				h.abortServiceError(ctx, err)
			}
			return
		}

		resultInfo := new(genResultInfo)
		resultInfo.RowsAffected = rowsAffected

		ctx.Payload(resultInfo)
	}
}
