// Code generated by cmd/handlergen. DO NOT EDIT.

package lesson_record

import (
	"edu-schedule-system/internal/pkg/core"
)

func RegisterGeneratedLessonRecordRoutes(h *Handler, r core.RouterGroup) {
	// 新增数据
	r.POST("/lesson_record", h.Create())

	// 获取列表数据
	r.GET("/lesson_records", h.List())

	// 根据 ID 获取数据
	r.GET("/lesson_record/:id", h.GetByID())

	// 根据 ID 更新数据
	r.PUT("/lesson_record/:id", h.UpdateByID())

	// 根据 ID 删除数据
	r.DELETE("/lesson_record/:id", h.DeleteByID())
}
