// Code generated by cmd/handlergen. DO NOT EDIT.

package reschedule_record

import (
	"errors"
	"net/http"
	"strconv"

	"edu-schedule-system/internal/code"
	"edu-schedule-system/internal/pkg/audit"
	"edu-schedule-system/internal/pkg/core"
	"edu-schedule-system/internal/service"
	"edu-schedule-system/internal/service/apperr"
	"edu-schedule-system/internal/service/dto"
	"edu-schedule-system/internal/service/reschedule_record"

	mysqlDriver "github.com/go-sql-driver/mysql"
	"go.uber.org/zap"
	"gorm.io/gorm"
)

type Handler struct {
	logger                  *zap.Logger
	rescheduleRecordService reschedule_record.Service
}

type genResultInfo struct {
	RowsAffected int64 `json:"rows_affected"`
}

func New(logger *zap.Logger, rescheduleRecordService reschedule_record.Service) *Handler {
	return &Handler{
		logger:                  logger,
		rescheduleRecordService: rescheduleRecordService,
	}
}

func (h *Handler) abortServiceError(ctx core.Context, err error) {
	var appErr *apperr.Error
	if errors.As(err, &appErr) {
		switch appErr.Kind {
		case apperr.KindInvalidArgument:
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				appErr.Message),
			)
		case apperr.KindNotFound:
			ctx.AbortWithError(core.Error(
				http.StatusNotFound,
				code.RecordNotFound,
				appErr.Message),
			)
		case apperr.KindConflict:
			ctx.AbortWithError(core.Error(
				http.StatusConflict,
				code.Conflict,
				appErr.Message),
			)
		case apperr.KindForbidden:
			ctx.AbortWithError(core.Error(
				http.StatusForbidden,
				code.Forbidden,
				appErr.Message),
			)
		case apperr.KindDependencyFailed:
			ctx.AbortWithError(core.Error(
				http.StatusServiceUnavailable,
				code.DependencyFailed,
				appErr.Message),
			)
		default:
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				appErr.Message),
			)
		}
		return
	}

	var mysqlErr *mysqlDriver.MySQLError
	if errors.As(err, &mysqlErr) {
		if mysqlErr.Number == 1062 || mysqlErr.Number == 1451 || mysqlErr.Number == 1452 || mysqlErr.Number == 3819 || mysqlErr.Number == 3822 {
			ctx.AbortWithError(core.Error(http.StatusConflict, code.Conflict, mysqlErr.Message))
			return
		}
	}

	ctx.AbortWithError(core.Error(
		http.StatusInternalServerError,
		code.ServerError,
		code.Text(code.ServerError)),
	)
}

func abortBadID(ctx core.Context) {
	ctx.AbortWithError(core.Error(
		http.StatusBadRequest,
		code.ParamBindError,
		"id must be a positive integer"),
	)
}

// Create 新增数据
// @Summary 新增数据
// @Description 新增数据
// @Tags Table.reschedule_record
// @Accept json
// @Produce json
// @Param RequestBody body dto.RescheduleRecordCreateRequest true "请求参数"
// @Success 200 {object} map[string]interface{}
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/reschedule_record [post]
func (h *Handler) Create() core.HandlerFunc {
	return func(ctx core.Context) {
		var req dto.RescheduleRecordCreateRequest
		if err := ctx.ShouldBindJSON(&req); err != nil {
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				err.Error()),
			)
			return
		}

		if err := service.EnsureDataScopeStudent(ctx.SessionUserInfo(), ctx.SessionUserInfo().Id); err != nil {
			h.abortServiceError(ctx, err)
			return
		}

		id, err := h.rescheduleRecordService.Create(ctx.RequestContext(), &req)
		if err != nil {
			h.abortServiceError(ctx, err)
			return
		}
		audit.Log(ctx, audit.Event{Action: "reschedule_record.create", Module: "reschedule_record", TargetID: id, Detail: audit.Detail("oldScheduleId", req.OldScheduleID, "newScheduleId", req.NewScheduleID, "operationType", req.OperationType)})

		ctx.Payload(map[string]interface{}{"id": id})
	}
}

// List 获取列表数据
// @Summary 获取列表数据
// @Description 获取列表数据
// @Tags Table.reschedule_record
// @Accept json
// @Produce json
// @Success 200 {object} []dto.RescheduleRecordResponse
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/reschedule_records [get]
func (h *Handler) List() core.HandlerFunc {
	return func(ctx core.Context) {
		query := dto.RescheduleRecordListQuery{}
		if err := ctx.ShouldBindQuery(&query); err != nil {
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				err.Error()),
			)
			return
		}

		list, err := h.rescheduleRecordService.List(ctx.RequestContext(), query)
		if err != nil {
			h.abortServiceError(ctx, err)
			return
		}

		ctx.Payload(list)
	}
}

// GetByID 根据 ID 获取数据
// @Summary 根据 ID 获取数据
// @Description 根据 ID 获取数据
// @Tags Table.reschedule_record
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} dto.RescheduleRecordResponse
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/reschedule_record/{id} [get]
func (h *Handler) GetByID() core.HandlerFunc {
	return func(ctx core.Context) {
		id, err := strconv.Atoi(ctx.Param("id"))
		if err != nil || id <= 0 {
			abortBadID(ctx)
			return
		}

		info, err := h.rescheduleRecordService.GetByID(ctx.RequestContext(), int32(id))
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				ctx.AbortWithError(core.Error(
					http.StatusNotFound,
					code.RecordNotFound,
					"record not found"),
				)
			} else {
				h.abortServiceError(ctx, err)
			}
			return
		}

		ctx.Payload(info)
	}
}

// DeleteByID 根据 ID 删除数据
// @Summary 根据 ID 删除数据
// @Description 根据 ID 删除数据
// @Tags Table.reschedule_record
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Success 200 {object} genResultInfo
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/reschedule_record/{id} [delete]
func (h *Handler) DeleteByID() core.HandlerFunc {
	return func(ctx core.Context) {
		id, err := strconv.Atoi(ctx.Param("id"))
		if err != nil || id <= 0 {
			abortBadID(ctx)
			return
		}

		rowsAffected, err := h.rescheduleRecordService.DeleteByID(ctx.RequestContext(), int32(id))
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				ctx.AbortWithError(core.Error(
					http.StatusNotFound,
					code.RecordNotFound,
					"record not found"),
				)
			} else {
				h.abortServiceError(ctx, err)
			}
			return
		}
		audit.Log(ctx, audit.Event{Action: "reschedule_record.delete", Module: "reschedule_record", TargetID: int32(id)})

		resultInfo := new(genResultInfo)
		resultInfo.RowsAffected = rowsAffected

		ctx.Payload(resultInfo)
	}
}

// UpdateByID 根据 ID 更新数据
// @Summary 根据 ID 更新数据
// @Description 根据 ID 更新数据
// @Tags Table.reschedule_record
// @Accept json
// @Produce json
// @Param id path string true "ID"
// @Param RequestBody body dto.RescheduleRecordUpdateRequest true "请求参数"
// @Success 200 {object} genResultInfo
// @Failure 400 {object} code.Failure
// @Security BearerAuth
// @Router /api/v1/reschedule_record/{id} [put]
func (h *Handler) UpdateByID() core.HandlerFunc {
	return func(ctx core.Context) {
		id, err := strconv.Atoi(ctx.Param("id"))
		if err != nil || id <= 0 {
			abortBadID(ctx)
			return
		}

		var updateData dto.RescheduleRecordUpdateRequest
		if err := ctx.ShouldBindJSON(&updateData); err != nil {
			ctx.AbortWithError(core.Error(
				http.StatusBadRequest,
				code.ParamBindError,
				err.Error()),
			)
			return
		}

		rowsAffected, err := h.rescheduleRecordService.UpdateByID(ctx.RequestContext(), int32(id), updateData)
		if err != nil {
			if errors.Is(err, gorm.ErrRecordNotFound) {
				ctx.AbortWithError(core.Error(
					http.StatusNotFound,
					code.RecordNotFound,
					"record not found"),
				)
			} else {
				h.abortServiceError(ctx, err)
			}
			return
		}
		audit.Log(ctx, audit.Event{Action: "reschedule_record.update", Module: "reschedule_record", TargetID: int32(id), Detail: audit.Detail("fields", updateData)})

		resultInfo := new(genResultInfo)
		resultInfo.RowsAffected = rowsAffected

		ctx.Payload(resultInfo)
	}
}
