// Code generated by cmd/handlergen. DO NOT EDIT.

package payment_record

import (
	"edu-schedule-system/internal/pkg/core"
)

func RegisterGeneratedPaymentRecordRoutes(h *Handler, r core.RouterGroup) {
	// 新增数据
	r.POST("/payment_record", h.Create())

	// 获取列表数据
	r.GET("/payment_records", h.List())

	// 根据 ID 获取数据
	r.GET("/payment_record/:id", h.GetByID())

	// 根据 ID 更新数据
	r.PUT("/payment_record/:id", h.UpdateByID())

	// 根据 ID 删除数据
	r.DELETE("/payment_record/:id", h.DeleteByID())
}
