// Code generated by cmd/handlergen. DO NOT EDIT.

package student

import (
	"edu-schedule-system/internal/pkg/core"
)

func RegisterGeneratedStudentRoutes(h *Handler, r core.RouterGroup) {
	// 新增数据
	r.POST("/student", h.Create())

	// 获取列表数据
	r.GET("/students", h.List())

	// 根据 ID 获取数据
	r.GET("/student/:id", h.GetByID())

	// 根据 ID 更新数据
	r.PUT("/student/:id", h.UpdateByID())

	// 根据 ID 删除数据
	r.DELETE("/student/:id", h.DeleteByID())
}
