// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newAuthRecoveryAudit(db *gorm.DB, opts ...gen.DOOption) authRecoveryAudit {
	_authRecoveryAudit := authRecoveryAudit{}

	_authRecoveryAudit.authRecoveryAuditDo.UseDB(db, opts...)
	_authRecoveryAudit.authRecoveryAuditDo.UseModel(&model.AuthRecoveryAudit{})

	tableName := _authRecoveryAudit.authRecoveryAuditDo.TableName()
	_authRecoveryAudit.ALL = field.NewAsterisk(tableName)
	_authRecoveryAudit.ID = field.NewString(tableName, "id")
	_authRecoveryAudit.ChallengeID = field.NewString(tableName, "challenge_id")
	_authRecoveryAudit.UserID = field.NewInt32(tableName, "user_id")
	_authRecoveryAudit.Action = field.NewString(tableName, "action")
	_authRecoveryAudit.Status = field.NewString(tableName, "status")
	_authRecoveryAudit.Detail = field.NewString(tableName, "detail")
	_authRecoveryAudit.ActorIP = field.NewString(tableName, "actor_ip")
	_authRecoveryAudit.UserAgent = field.NewString(tableName, "user_agent")
	_authRecoveryAudit.CreatedAt = field.NewTime(tableName, "created_at")

	_authRecoveryAudit.fillFieldMap()

	return _authRecoveryAudit
}

// authRecoveryAudit 账户恢复审计表
type authRecoveryAudit struct {
	authRecoveryAuditDo

	ALL         field.Asterisk
	ID          field.String // 审计ID
	ChallengeID field.String // 恢复挑战ID
	UserID      field.Int32  // 用户ID
	Action      field.String // 动作
	Status      field.String // 状态
	Detail      field.String // 详情
	ActorIP     field.String // 操作者IP
	UserAgent   field.String // 操作者UA
	CreatedAt   field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (a authRecoveryAudit) Table(newTableName string) *authRecoveryAudit {
	a.authRecoveryAuditDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authRecoveryAudit) As(alias string) *authRecoveryAudit {
	a.authRecoveryAuditDo.DO = *(a.authRecoveryAuditDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authRecoveryAudit) updateTableName(table string) *authRecoveryAudit {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.ChallengeID = field.NewString(table, "challenge_id")
	a.UserID = field.NewInt32(table, "user_id")
	a.Action = field.NewString(table, "action")
	a.Status = field.NewString(table, "status")
	a.Detail = field.NewString(table, "detail")
	a.ActorIP = field.NewString(table, "actor_ip")
	a.UserAgent = field.NewString(table, "user_agent")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *authRecoveryAudit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authRecoveryAudit) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 9)
	a.fieldMap["id"] = a.ID
	a.fieldMap["challenge_id"] = a.ChallengeID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["action"] = a.Action
	a.fieldMap["status"] = a.Status
	a.fieldMap["detail"] = a.Detail
	a.fieldMap["actor_ip"] = a.ActorIP
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a authRecoveryAudit) clone(db *gorm.DB) authRecoveryAudit {
	a.authRecoveryAuditDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authRecoveryAudit) replaceDB(db *gorm.DB) authRecoveryAudit {
	a.authRecoveryAuditDo.ReplaceDB(db)
	return a
}

type authRecoveryAuditDo struct{ gen.DO }

func (a authRecoveryAuditDo) Debug() *authRecoveryAuditDo {
	return a.withDO(a.DO.Debug())
}

func (a authRecoveryAuditDo) WithContext(ctx context.Context) *authRecoveryAuditDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authRecoveryAuditDo) ReadDB() *authRecoveryAuditDo {
	return a.Clauses(dbresolver.Read)
}

func (a authRecoveryAuditDo) WriteDB() *authRecoveryAuditDo {
	return a.Clauses(dbresolver.Write)
}

func (a authRecoveryAuditDo) Session(config *gorm.Session) *authRecoveryAuditDo {
	return a.withDO(a.DO.Session(config))
}

func (a authRecoveryAuditDo) Clauses(conds ...clause.Expression) *authRecoveryAuditDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authRecoveryAuditDo) Returning(value interface{}, columns ...string) *authRecoveryAuditDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authRecoveryAuditDo) Not(conds ...gen.Condition) *authRecoveryAuditDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authRecoveryAuditDo) Or(conds ...gen.Condition) *authRecoveryAuditDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authRecoveryAuditDo) Select(conds ...field.Expr) *authRecoveryAuditDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authRecoveryAuditDo) Where(conds ...gen.Condition) *authRecoveryAuditDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authRecoveryAuditDo) Order(conds ...field.Expr) *authRecoveryAuditDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authRecoveryAuditDo) Distinct(cols ...field.Expr) *authRecoveryAuditDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authRecoveryAuditDo) Omit(cols ...field.Expr) *authRecoveryAuditDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authRecoveryAuditDo) Join(table schema.Tabler, on ...field.Expr) *authRecoveryAuditDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authRecoveryAuditDo) LeftJoin(table schema.Tabler, on ...field.Expr) *authRecoveryAuditDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authRecoveryAuditDo) RightJoin(table schema.Tabler, on ...field.Expr) *authRecoveryAuditDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authRecoveryAuditDo) Group(cols ...field.Expr) *authRecoveryAuditDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authRecoveryAuditDo) Having(conds ...gen.Condition) *authRecoveryAuditDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authRecoveryAuditDo) Limit(limit int) *authRecoveryAuditDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authRecoveryAuditDo) Offset(offset int) *authRecoveryAuditDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authRecoveryAuditDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *authRecoveryAuditDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authRecoveryAuditDo) Unscoped() *authRecoveryAuditDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authRecoveryAuditDo) Create(values ...*model.AuthRecoveryAudit) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authRecoveryAuditDo) CreateInBatches(values []*model.AuthRecoveryAudit, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authRecoveryAuditDo) Save(values ...*model.AuthRecoveryAudit) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authRecoveryAuditDo) First() (*model.AuthRecoveryAudit, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryAudit), nil
	}
}

func (a authRecoveryAuditDo) Take() (*model.AuthRecoveryAudit, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryAudit), nil
	}
}

func (a authRecoveryAuditDo) Last() (*model.AuthRecoveryAudit, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryAudit), nil
	}
}

func (a authRecoveryAuditDo) Find() ([]*model.AuthRecoveryAudit, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuthRecoveryAudit), err
}

func (a authRecoveryAuditDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthRecoveryAudit, err error) {
	buf := make([]*model.AuthRecoveryAudit, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authRecoveryAuditDo) FindInBatches(result *[]*model.AuthRecoveryAudit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authRecoveryAuditDo) Attrs(attrs ...field.AssignExpr) *authRecoveryAuditDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authRecoveryAuditDo) Assign(attrs ...field.AssignExpr) *authRecoveryAuditDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authRecoveryAuditDo) Joins(fields ...field.RelationField) *authRecoveryAuditDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authRecoveryAuditDo) Preload(fields ...field.RelationField) *authRecoveryAuditDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authRecoveryAuditDo) FirstOrInit() (*model.AuthRecoveryAudit, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryAudit), nil
	}
}

func (a authRecoveryAuditDo) FirstOrCreate() (*model.AuthRecoveryAudit, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryAudit), nil
	}
}

func (a authRecoveryAuditDo) FindByPage(offset int, limit int) (result []*model.AuthRecoveryAudit, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authRecoveryAuditDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authRecoveryAuditDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authRecoveryAuditDo) Delete(models ...*model.AuthRecoveryAudit) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authRecoveryAuditDo) withDO(do gen.Dao) *authRecoveryAuditDo {
	a.DO = *do.(*gen.DO)
	return a
}
