// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newAuthSession(db *gorm.DB, opts ...gen.DOOption) authSession {
	_authSession := authSession{}

	_authSession.authSessionDo.UseDB(db, opts...)
	_authSession.authSessionDo.UseModel(&model.AuthSession{})

	tableName := _authSession.authSessionDo.TableName()
	_authSession.ALL = field.NewAsterisk(tableName)
	_authSession.ID = field.NewString(tableName, "id")
	_authSession.UserID = field.NewInt32(tableName, "user_id")
	_authSession.OrganizationID = field.NewInt32(tableName, "organization_id")
	_authSession.CampusID = field.NewInt32(tableName, "campus_id")
	_authSession.RoleCode = field.NewString(tableName, "role_code")
	_authSession.DeviceID = field.NewString(tableName, "device_id")
	_authSession.DeviceName = field.NewString(tableName, "device_name")
	_authSession.ClientIP = field.NewString(tableName, "client_ip")
	_authSession.UserAgent = field.NewString(tableName, "user_agent")
	_authSession.UserAgentHash = field.NewString(tableName, "user_agent_hash")
	_authSession.AccessTokenID = field.NewString(tableName, "access_token_id")
	_authSession.RefreshTokenID = field.NewString(tableName, "refresh_token_id")
	_authSession.RefreshTokenHash = field.NewString(tableName, "refresh_token_hash")
	_authSession.Status = field.NewString(tableName, "status")
	_authSession.IsSuspicious = field.NewBool(tableName, "is_suspicious")
	_authSession.RiskFlags = field.NewString(tableName, "risk_flags")
	_authSession.LastSeenAt = field.NewTime(tableName, "last_seen_at")
	_authSession.LastRefreshedAt = field.NewTime(tableName, "last_refreshed_at")
	_authSession.RevokedAt = field.NewTime(tableName, "revoked_at")
	_authSession.RevokedReason = field.NewString(tableName, "revoked_reason")
	_authSession.RecoveryVerifiedAt = field.NewTime(tableName, "recovery_verified_at")
	_authSession.CreatedAt = field.NewTime(tableName, "created_at")
	_authSession.UpdatedAt = field.NewTime(tableName, "updated_at")

	_authSession.fillFieldMap()

	return _authSession
}

// authSession 认证会话表
type authSession struct {
	authSessionDo

	ALL                field.Asterisk
	ID                 field.String // 会话ID
	UserID             field.Int32  // 用户ID
	OrganizationID     field.Int32  // 所属机构ID快照
	CampusID           field.Int32  // 所属校区ID快照
	RoleCode           field.String // 角色编码快照
	DeviceID           field.String // 设备指纹ID
	DeviceName         field.String // 设备名称
	ClientIP           field.String // 登录/刷新IP
	UserAgent          field.String // 客户端UA
	UserAgentHash      field.String // UA哈希
	AccessTokenID      field.String // 当前 access token id
	RefreshTokenID     field.String // 当前 refresh token id
	RefreshTokenHash   field.String // refresh token 摘要
	Status             field.String // active/revoked
	IsSuspicious       field.Bool   // 是否异常会话
	RiskFlags          field.String // 风险标签
	LastSeenAt         field.Time   // 最近活跃时间
	LastRefreshedAt    field.Time   // 最近刷新时间
	RevokedAt          field.Time   // 撤销时间
	RevokedReason      field.String // 撤销原因
	RecoveryVerifiedAt field.Time   // 因恢复流程被校验的时间
	CreatedAt          field.Time   // 创建时间
	UpdatedAt          field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a authSession) Table(newTableName string) *authSession {
	a.authSessionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authSession) As(alias string) *authSession {
	a.authSessionDo.DO = *(a.authSessionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authSession) updateTableName(table string) *authSession {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.UserID = field.NewInt32(table, "user_id")
	a.OrganizationID = field.NewInt32(table, "organization_id")
	a.CampusID = field.NewInt32(table, "campus_id")
	a.RoleCode = field.NewString(table, "role_code")
	a.DeviceID = field.NewString(table, "device_id")
	a.DeviceName = field.NewString(table, "device_name")
	a.ClientIP = field.NewString(table, "client_ip")
	a.UserAgent = field.NewString(table, "user_agent")
	a.UserAgentHash = field.NewString(table, "user_agent_hash")
	a.AccessTokenID = field.NewString(table, "access_token_id")
	a.RefreshTokenID = field.NewString(table, "refresh_token_id")
	a.RefreshTokenHash = field.NewString(table, "refresh_token_hash")
	a.Status = field.NewString(table, "status")
	a.IsSuspicious = field.NewBool(table, "is_suspicious")
	a.RiskFlags = field.NewString(table, "risk_flags")
	a.LastSeenAt = field.NewTime(table, "last_seen_at")
	a.LastRefreshedAt = field.NewTime(table, "last_refreshed_at")
	a.RevokedAt = field.NewTime(table, "revoked_at")
	a.RevokedReason = field.NewString(table, "revoked_reason")
	a.RecoveryVerifiedAt = field.NewTime(table, "recovery_verified_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *authSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authSession) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 23)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["organization_id"] = a.OrganizationID
	a.fieldMap["campus_id"] = a.CampusID
	a.fieldMap["role_code"] = a.RoleCode
	a.fieldMap["device_id"] = a.DeviceID
	a.fieldMap["device_name"] = a.DeviceName
	a.fieldMap["client_ip"] = a.ClientIP
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["user_agent_hash"] = a.UserAgentHash
	a.fieldMap["access_token_id"] = a.AccessTokenID
	a.fieldMap["refresh_token_id"] = a.RefreshTokenID
	a.fieldMap["refresh_token_hash"] = a.RefreshTokenHash
	a.fieldMap["status"] = a.Status
	a.fieldMap["is_suspicious"] = a.IsSuspicious
	a.fieldMap["risk_flags"] = a.RiskFlags
	a.fieldMap["last_seen_at"] = a.LastSeenAt
	a.fieldMap["last_refreshed_at"] = a.LastRefreshedAt
	a.fieldMap["revoked_at"] = a.RevokedAt
	a.fieldMap["revoked_reason"] = a.RevokedReason
	a.fieldMap["recovery_verified_at"] = a.RecoveryVerifiedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a authSession) clone(db *gorm.DB) authSession {
	a.authSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authSession) replaceDB(db *gorm.DB) authSession {
	a.authSessionDo.ReplaceDB(db)
	return a
}

type authSessionDo struct{ gen.DO }

func (a authSessionDo) Debug() *authSessionDo {
	return a.withDO(a.DO.Debug())
}

func (a authSessionDo) WithContext(ctx context.Context) *authSessionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authSessionDo) ReadDB() *authSessionDo {
	return a.Clauses(dbresolver.Read)
}

func (a authSessionDo) WriteDB() *authSessionDo {
	return a.Clauses(dbresolver.Write)
}

func (a authSessionDo) Session(config *gorm.Session) *authSessionDo {
	return a.withDO(a.DO.Session(config))
}

func (a authSessionDo) Clauses(conds ...clause.Expression) *authSessionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authSessionDo) Returning(value interface{}, columns ...string) *authSessionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authSessionDo) Not(conds ...gen.Condition) *authSessionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authSessionDo) Or(conds ...gen.Condition) *authSessionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authSessionDo) Select(conds ...field.Expr) *authSessionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authSessionDo) Where(conds ...gen.Condition) *authSessionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authSessionDo) Order(conds ...field.Expr) *authSessionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authSessionDo) Distinct(cols ...field.Expr) *authSessionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authSessionDo) Omit(cols ...field.Expr) *authSessionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authSessionDo) Join(table schema.Tabler, on ...field.Expr) *authSessionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *authSessionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) *authSessionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authSessionDo) Group(cols ...field.Expr) *authSessionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authSessionDo) Having(conds ...gen.Condition) *authSessionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authSessionDo) Limit(limit int) *authSessionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authSessionDo) Offset(offset int) *authSessionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *authSessionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authSessionDo) Unscoped() *authSessionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authSessionDo) Create(values ...*model.AuthSession) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authSessionDo) CreateInBatches(values []*model.AuthSession, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authSessionDo) Save(values ...*model.AuthSession) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authSessionDo) First() (*model.AuthSession, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) Take() (*model.AuthSession, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) Last() (*model.AuthSession, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) Find() ([]*model.AuthSession, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuthSession), err
}

func (a authSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthSession, err error) {
	buf := make([]*model.AuthSession, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authSessionDo) FindInBatches(result *[]*model.AuthSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authSessionDo) Attrs(attrs ...field.AssignExpr) *authSessionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authSessionDo) Assign(attrs ...field.AssignExpr) *authSessionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authSessionDo) Joins(fields ...field.RelationField) *authSessionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authSessionDo) Preload(fields ...field.RelationField) *authSessionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authSessionDo) FirstOrInit() (*model.AuthSession, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) FirstOrCreate() (*model.AuthSession, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthSession), nil
	}
}

func (a authSessionDo) FindByPage(offset int, limit int) (result []*model.AuthSession, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authSessionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authSessionDo) Delete(models ...*model.AuthSession) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authSessionDo) withDO(do gen.Dao) *authSessionDo {
	a.DO = *do.(*gen.DO)
	return a
}
