// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newAuthRecoveryChallenge(db *gorm.DB, opts ...gen.DOOption) authRecoveryChallenge {
	_authRecoveryChallenge := authRecoveryChallenge{}

	_authRecoveryChallenge.authRecoveryChallengeDo.UseDB(db, opts...)
	_authRecoveryChallenge.authRecoveryChallengeDo.UseModel(&model.AuthRecoveryChallenge{})

	tableName := _authRecoveryChallenge.authRecoveryChallengeDo.TableName()
	_authRecoveryChallenge.ALL = field.NewAsterisk(tableName)
	_authRecoveryChallenge.ID = field.NewString(tableName, "id")
	_authRecoveryChallenge.UserID = field.NewInt32(tableName, "user_id")
	_authRecoveryChallenge.Username = field.NewString(tableName, "username")
	_authRecoveryChallenge.Channel = field.NewString(tableName, "channel")
	_authRecoveryChallenge.ChannelTarget = field.NewString(tableName, "channel_target")
	_authRecoveryChallenge.CodeHash = field.NewString(tableName, "code_hash")
	_authRecoveryChallenge.SecondChannel = field.NewString(tableName, "second_channel")
	_authRecoveryChallenge.SecondChannelTarget = field.NewString(tableName, "second_channel_target")
	_authRecoveryChallenge.SecondCodeHash = field.NewString(tableName, "second_code_hash")
	_authRecoveryChallenge.Status = field.NewString(tableName, "status")
	_authRecoveryChallenge.RiskFlags = field.NewString(tableName, "risk_flags")
	_authRecoveryChallenge.RequestedIP = field.NewString(tableName, "requested_ip")
	_authRecoveryChallenge.RequestedUserAgent = field.NewString(tableName, "requested_user_agent")
	_authRecoveryChallenge.ExpiresAt = field.NewTime(tableName, "expires_at")
	_authRecoveryChallenge.VerifiedAt = field.NewTime(tableName, "verified_at")
	_authRecoveryChallenge.ConsumedAt = field.NewTime(tableName, "consumed_at")
	_authRecoveryChallenge.CreatedAt = field.NewTime(tableName, "created_at")
	_authRecoveryChallenge.UpdatedAt = field.NewTime(tableName, "updated_at")

	_authRecoveryChallenge.fillFieldMap()

	return _authRecoveryChallenge
}

// authRecoveryChallenge 账户恢复挑战表
type authRecoveryChallenge struct {
	authRecoveryChallengeDo

	ALL                 field.Asterisk
	ID                  field.String // 恢复挑战ID
	UserID              field.Int32  // 用户ID
	Username            field.String // 用户名快照
	Channel             field.String // 主验证通道 email/sms
	ChannelTarget       field.String // 主验证目标
	CodeHash            field.String // 主验证码摘要
	SecondChannel       field.String // 二次验证通道
	SecondChannelTarget field.String // 二次验证目标
	SecondCodeHash      field.String // 二次验证码摘要
	Status              field.String // pending/verified/consumed/expired
	RiskFlags           field.String // 恢复风险标签
	RequestedIP         field.String // 请求IP
	RequestedUserAgent  field.String // 请求UA
	ExpiresAt           field.Time   // 过期时间
	VerifiedAt          field.Time   // 验证完成时间
	ConsumedAt          field.Time   // 消费时间
	CreatedAt           field.Time   // 创建时间
	UpdatedAt           field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (a authRecoveryChallenge) Table(newTableName string) *authRecoveryChallenge {
	a.authRecoveryChallengeDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a authRecoveryChallenge) As(alias string) *authRecoveryChallenge {
	a.authRecoveryChallengeDo.DO = *(a.authRecoveryChallengeDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *authRecoveryChallenge) updateTableName(table string) *authRecoveryChallenge {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewString(table, "id")
	a.UserID = field.NewInt32(table, "user_id")
	a.Username = field.NewString(table, "username")
	a.Channel = field.NewString(table, "channel")
	a.ChannelTarget = field.NewString(table, "channel_target")
	a.CodeHash = field.NewString(table, "code_hash")
	a.SecondChannel = field.NewString(table, "second_channel")
	a.SecondChannelTarget = field.NewString(table, "second_channel_target")
	a.SecondCodeHash = field.NewString(table, "second_code_hash")
	a.Status = field.NewString(table, "status")
	a.RiskFlags = field.NewString(table, "risk_flags")
	a.RequestedIP = field.NewString(table, "requested_ip")
	a.RequestedUserAgent = field.NewString(table, "requested_user_agent")
	a.ExpiresAt = field.NewTime(table, "expires_at")
	a.VerifiedAt = field.NewTime(table, "verified_at")
	a.ConsumedAt = field.NewTime(table, "consumed_at")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *authRecoveryChallenge) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *authRecoveryChallenge) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 18)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["username"] = a.Username
	a.fieldMap["channel"] = a.Channel
	a.fieldMap["channel_target"] = a.ChannelTarget
	a.fieldMap["code_hash"] = a.CodeHash
	a.fieldMap["second_channel"] = a.SecondChannel
	a.fieldMap["second_channel_target"] = a.SecondChannelTarget
	a.fieldMap["second_code_hash"] = a.SecondCodeHash
	a.fieldMap["status"] = a.Status
	a.fieldMap["risk_flags"] = a.RiskFlags
	a.fieldMap["requested_ip"] = a.RequestedIP
	a.fieldMap["requested_user_agent"] = a.RequestedUserAgent
	a.fieldMap["expires_at"] = a.ExpiresAt
	a.fieldMap["verified_at"] = a.VerifiedAt
	a.fieldMap["consumed_at"] = a.ConsumedAt
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a authRecoveryChallenge) clone(db *gorm.DB) authRecoveryChallenge {
	a.authRecoveryChallengeDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a authRecoveryChallenge) replaceDB(db *gorm.DB) authRecoveryChallenge {
	a.authRecoveryChallengeDo.ReplaceDB(db)
	return a
}

type authRecoveryChallengeDo struct{ gen.DO }

func (a authRecoveryChallengeDo) Debug() *authRecoveryChallengeDo {
	return a.withDO(a.DO.Debug())
}

func (a authRecoveryChallengeDo) WithContext(ctx context.Context) *authRecoveryChallengeDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a authRecoveryChallengeDo) ReadDB() *authRecoveryChallengeDo {
	return a.Clauses(dbresolver.Read)
}

func (a authRecoveryChallengeDo) WriteDB() *authRecoveryChallengeDo {
	return a.Clauses(dbresolver.Write)
}

func (a authRecoveryChallengeDo) Session(config *gorm.Session) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Session(config))
}

func (a authRecoveryChallengeDo) Clauses(conds ...clause.Expression) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a authRecoveryChallengeDo) Returning(value interface{}, columns ...string) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a authRecoveryChallengeDo) Not(conds ...gen.Condition) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a authRecoveryChallengeDo) Or(conds ...gen.Condition) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a authRecoveryChallengeDo) Select(conds ...field.Expr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a authRecoveryChallengeDo) Where(conds ...gen.Condition) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a authRecoveryChallengeDo) Order(conds ...field.Expr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a authRecoveryChallengeDo) Distinct(cols ...field.Expr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a authRecoveryChallengeDo) Omit(cols ...field.Expr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a authRecoveryChallengeDo) Join(table schema.Tabler, on ...field.Expr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a authRecoveryChallengeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a authRecoveryChallengeDo) RightJoin(table schema.Tabler, on ...field.Expr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a authRecoveryChallengeDo) Group(cols ...field.Expr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a authRecoveryChallengeDo) Having(conds ...gen.Condition) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a authRecoveryChallengeDo) Limit(limit int) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a authRecoveryChallengeDo) Offset(offset int) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a authRecoveryChallengeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a authRecoveryChallengeDo) Unscoped() *authRecoveryChallengeDo {
	return a.withDO(a.DO.Unscoped())
}

func (a authRecoveryChallengeDo) Create(values ...*model.AuthRecoveryChallenge) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a authRecoveryChallengeDo) CreateInBatches(values []*model.AuthRecoveryChallenge, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a authRecoveryChallengeDo) Save(values ...*model.AuthRecoveryChallenge) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a authRecoveryChallengeDo) First() (*model.AuthRecoveryChallenge, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryChallenge), nil
	}
}

func (a authRecoveryChallengeDo) Take() (*model.AuthRecoveryChallenge, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryChallenge), nil
	}
}

func (a authRecoveryChallengeDo) Last() (*model.AuthRecoveryChallenge, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryChallenge), nil
	}
}

func (a authRecoveryChallengeDo) Find() ([]*model.AuthRecoveryChallenge, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuthRecoveryChallenge), err
}

func (a authRecoveryChallengeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuthRecoveryChallenge, err error) {
	buf := make([]*model.AuthRecoveryChallenge, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a authRecoveryChallengeDo) FindInBatches(result *[]*model.AuthRecoveryChallenge, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a authRecoveryChallengeDo) Attrs(attrs ...field.AssignExpr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a authRecoveryChallengeDo) Assign(attrs ...field.AssignExpr) *authRecoveryChallengeDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a authRecoveryChallengeDo) Joins(fields ...field.RelationField) *authRecoveryChallengeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a authRecoveryChallengeDo) Preload(fields ...field.RelationField) *authRecoveryChallengeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a authRecoveryChallengeDo) FirstOrInit() (*model.AuthRecoveryChallenge, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryChallenge), nil
	}
}

func (a authRecoveryChallengeDo) FirstOrCreate() (*model.AuthRecoveryChallenge, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuthRecoveryChallenge), nil
	}
}

func (a authRecoveryChallengeDo) FindByPage(offset int, limit int) (result []*model.AuthRecoveryChallenge, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a authRecoveryChallengeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a authRecoveryChallengeDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a authRecoveryChallengeDo) Delete(models ...*model.AuthRecoveryChallenge) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *authRecoveryChallengeDo) withDO(do gen.Dao) *authRecoveryChallengeDo {
	a.DO = *do.(*gen.DO)
	return a
}
