// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newCampus(db *gorm.DB, opts ...gen.DOOption) campus {
	_campus := campus{}

	_campus.campusDo.UseDB(db, opts...)
	_campus.campusDo.UseModel(&model.Campus{})

	tableName := _campus.campusDo.TableName()
	_campus.ALL = field.NewAsterisk(tableName)
	_campus.ID = field.NewInt32(tableName, "id")
	_campus.OrganizationID = field.NewInt32(tableName, "organization_id")
	_campus.CampusCode = field.NewString(tableName, "campus_code")
	_campus.CampusName = field.NewString(tableName, "campus_name")
	_campus.Status = field.NewString(tableName, "status")
	_campus.FeatureFlags = field.NewString(tableName, "feature_flags")
	_campus.Remark = field.NewString(tableName, "remark")
	_campus.CreatedAt = field.NewTime(tableName, "created_at")
	_campus.UpdatedAt = field.NewTime(tableName, "updated_at")

	_campus.fillFieldMap()

	return _campus
}

// campus 校区表
type campus struct {
	campusDo

	ALL            field.Asterisk
	ID             field.Int32  // 主键ID
	OrganizationID field.Int32  // 机构ID
	CampusCode     field.String // 校区编码
	CampusName     field.String // 校区名称
	Status         field.String // 状态：active/inactive
	FeatureFlags   field.String // 校区级功能开关
	Remark         field.String // 备注
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (c campus) Table(newTableName string) *campus {
	c.campusDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c campus) As(alias string) *campus {
	c.campusDo.DO = *(c.campusDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *campus) updateTableName(table string) *campus {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt32(table, "id")
	c.OrganizationID = field.NewInt32(table, "organization_id")
	c.CampusCode = field.NewString(table, "campus_code")
	c.CampusName = field.NewString(table, "campus_name")
	c.Status = field.NewString(table, "status")
	c.FeatureFlags = field.NewString(table, "feature_flags")
	c.Remark = field.NewString(table, "remark")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *campus) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *campus) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 9)
	c.fieldMap["id"] = c.ID
	c.fieldMap["organization_id"] = c.OrganizationID
	c.fieldMap["campus_code"] = c.CampusCode
	c.fieldMap["campus_name"] = c.CampusName
	c.fieldMap["status"] = c.Status
	c.fieldMap["feature_flags"] = c.FeatureFlags
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c campus) clone(db *gorm.DB) campus {
	c.campusDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c campus) replaceDB(db *gorm.DB) campus {
	c.campusDo.ReplaceDB(db)
	return c
}

type campusDo struct{ gen.DO }

func (c campusDo) Debug() *campusDo {
	return c.withDO(c.DO.Debug())
}

func (c campusDo) WithContext(ctx context.Context) *campusDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c campusDo) ReadDB() *campusDo {
	return c.Clauses(dbresolver.Read)
}

func (c campusDo) WriteDB() *campusDo {
	return c.Clauses(dbresolver.Write)
}

func (c campusDo) Session(config *gorm.Session) *campusDo {
	return c.withDO(c.DO.Session(config))
}

func (c campusDo) Clauses(conds ...clause.Expression) *campusDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c campusDo) Returning(value interface{}, columns ...string) *campusDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c campusDo) Not(conds ...gen.Condition) *campusDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c campusDo) Or(conds ...gen.Condition) *campusDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c campusDo) Select(conds ...field.Expr) *campusDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c campusDo) Where(conds ...gen.Condition) *campusDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c campusDo) Order(conds ...field.Expr) *campusDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c campusDo) Distinct(cols ...field.Expr) *campusDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c campusDo) Omit(cols ...field.Expr) *campusDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c campusDo) Join(table schema.Tabler, on ...field.Expr) *campusDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c campusDo) LeftJoin(table schema.Tabler, on ...field.Expr) *campusDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c campusDo) RightJoin(table schema.Tabler, on ...field.Expr) *campusDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c campusDo) Group(cols ...field.Expr) *campusDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c campusDo) Having(conds ...gen.Condition) *campusDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c campusDo) Limit(limit int) *campusDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c campusDo) Offset(offset int) *campusDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c campusDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *campusDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c campusDo) Unscoped() *campusDo {
	return c.withDO(c.DO.Unscoped())
}

func (c campusDo) Create(values ...*model.Campus) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c campusDo) CreateInBatches(values []*model.Campus, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c campusDo) Save(values ...*model.Campus) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c campusDo) First() (*model.Campus, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Campus), nil
	}
}

func (c campusDo) Take() (*model.Campus, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Campus), nil
	}
}

func (c campusDo) Last() (*model.Campus, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Campus), nil
	}
}

func (c campusDo) Find() ([]*model.Campus, error) {
	result, err := c.DO.Find()
	return result.([]*model.Campus), err
}

func (c campusDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Campus, err error) {
	buf := make([]*model.Campus, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c campusDo) FindInBatches(result *[]*model.Campus, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c campusDo) Attrs(attrs ...field.AssignExpr) *campusDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c campusDo) Assign(attrs ...field.AssignExpr) *campusDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c campusDo) Joins(fields ...field.RelationField) *campusDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c campusDo) Preload(fields ...field.RelationField) *campusDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c campusDo) FirstOrInit() (*model.Campus, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Campus), nil
	}
}

func (c campusDo) FirstOrCreate() (*model.Campus, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Campus), nil
	}
}

func (c campusDo) FindByPage(offset int, limit int) (result []*model.Campus, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c campusDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c campusDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c campusDo) Delete(models ...*model.Campus) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *campusDo) withDO(do gen.Dao) *campusDo {
	c.DO = *do.(*gen.DO)
	return c
}
