// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                     = new(Query)
	Admin                 *admin
	AuthRecoveryAudit     *authRecoveryAudit
	AuthRecoveryChallenge *authRecoveryChallenge
	AuthSession           *authSession
	Campus                *campus
	Course                *course
	LessonPackage         *lessonPackage
	LessonRecord          *lessonRecord
	Organization          *organization
	PaymentRecord         *paymentRecord
	RescheduleRecord      *rescheduleRecord
	Schedule              *schedule
	SchemaMigrations      *schemaMigrations
	Student               *student
	Subscription          *subscription
	SysUser               *sysUser
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Admin = &Q.Admin
	AuthRecoveryAudit = &Q.AuthRecoveryAudit
	AuthRecoveryChallenge = &Q.AuthRecoveryChallenge
	AuthSession = &Q.AuthSession
	Campus = &Q.Campus
	Course = &Q.Course
	LessonPackage = &Q.LessonPackage
	LessonRecord = &Q.LessonRecord
	Organization = &Q.Organization
	PaymentRecord = &Q.PaymentRecord
	RescheduleRecord = &Q.RescheduleRecord
	Schedule = &Q.Schedule
	SchemaMigrations = &Q.SchemaMigrations
	Student = &Q.Student
	Subscription = &Q.Subscription
	SysUser = &Q.SysUser
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		Admin:                 newAdmin(db, opts...),
		AuthRecoveryAudit:     newAuthRecoveryAudit(db, opts...),
		AuthRecoveryChallenge: newAuthRecoveryChallenge(db, opts...),
		AuthSession:           newAuthSession(db, opts...),
		Campus:                newCampus(db, opts...),
		Course:                newCourse(db, opts...),
		LessonPackage:         newLessonPackage(db, opts...),
		LessonRecord:          newLessonRecord(db, opts...),
		Organization:          newOrganization(db, opts...),
		PaymentRecord:         newPaymentRecord(db, opts...),
		RescheduleRecord:      newRescheduleRecord(db, opts...),
		Schedule:              newSchedule(db, opts...),
		SchemaMigrations:      newSchemaMigrations(db, opts...),
		Student:               newStudent(db, opts...),
		Subscription:          newSubscription(db, opts...),
		SysUser:               newSysUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin                 admin
	AuthRecoveryAudit     authRecoveryAudit
	AuthRecoveryChallenge authRecoveryChallenge
	AuthSession           authSession
	Campus                campus
	Course                course
	LessonPackage         lessonPackage
	LessonRecord          lessonRecord
	Organization          organization
	PaymentRecord         paymentRecord
	RescheduleRecord      rescheduleRecord
	Schedule              schedule
	SchemaMigrations      schemaMigrations
	Student               student
	Subscription          subscription
	SysUser               sysUser
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Admin:                 q.Admin.clone(db),
		AuthRecoveryAudit:     q.AuthRecoveryAudit.clone(db),
		AuthRecoveryChallenge: q.AuthRecoveryChallenge.clone(db),
		AuthSession:           q.AuthSession.clone(db),
		Campus:                q.Campus.clone(db),
		Course:                q.Course.clone(db),
		LessonPackage:         q.LessonPackage.clone(db),
		LessonRecord:          q.LessonRecord.clone(db),
		Organization:          q.Organization.clone(db),
		PaymentRecord:         q.PaymentRecord.clone(db),
		RescheduleRecord:      q.RescheduleRecord.clone(db),
		Schedule:              q.Schedule.clone(db),
		SchemaMigrations:      q.SchemaMigrations.clone(db),
		Student:               q.Student.clone(db),
		Subscription:          q.Subscription.clone(db),
		SysUser:               q.SysUser.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Admin:                 q.Admin.replaceDB(db),
		AuthRecoveryAudit:     q.AuthRecoveryAudit.replaceDB(db),
		AuthRecoveryChallenge: q.AuthRecoveryChallenge.replaceDB(db),
		AuthSession:           q.AuthSession.replaceDB(db),
		Campus:                q.Campus.replaceDB(db),
		Course:                q.Course.replaceDB(db),
		LessonPackage:         q.LessonPackage.replaceDB(db),
		LessonRecord:          q.LessonRecord.replaceDB(db),
		Organization:          q.Organization.replaceDB(db),
		PaymentRecord:         q.PaymentRecord.replaceDB(db),
		RescheduleRecord:      q.RescheduleRecord.replaceDB(db),
		Schedule:              q.Schedule.replaceDB(db),
		SchemaMigrations:      q.SchemaMigrations.replaceDB(db),
		Student:               q.Student.replaceDB(db),
		Subscription:          q.Subscription.replaceDB(db),
		SysUser:               q.SysUser.replaceDB(db),
	}
}

type queryCtx struct {
	Admin                 *adminDo
	AuthRecoveryAudit     *authRecoveryAuditDo
	AuthRecoveryChallenge *authRecoveryChallengeDo
	AuthSession           *authSessionDo
	Campus                *campusDo
	Course                *courseDo
	LessonPackage         *lessonPackageDo
	LessonRecord          *lessonRecordDo
	Organization          *organizationDo
	PaymentRecord         *paymentRecordDo
	RescheduleRecord      *rescheduleRecordDo
	Schedule              *scheduleDo
	SchemaMigrations      *schemaMigrationsDo
	Student               *studentDo
	Subscription          *subscriptionDo
	SysUser               *sysUserDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:                 q.Admin.WithContext(ctx),
		AuthRecoveryAudit:     q.AuthRecoveryAudit.WithContext(ctx),
		AuthRecoveryChallenge: q.AuthRecoveryChallenge.WithContext(ctx),
		AuthSession:           q.AuthSession.WithContext(ctx),
		Campus:                q.Campus.WithContext(ctx),
		Course:                q.Course.WithContext(ctx),
		LessonPackage:         q.LessonPackage.WithContext(ctx),
		LessonRecord:          q.LessonRecord.WithContext(ctx),
		Organization:          q.Organization.WithContext(ctx),
		PaymentRecord:         q.PaymentRecord.WithContext(ctx),
		RescheduleRecord:      q.RescheduleRecord.WithContext(ctx),
		Schedule:              q.Schedule.WithContext(ctx),
		SchemaMigrations:      q.SchemaMigrations.WithContext(ctx),
		Student:               q.Student.WithContext(ctx),
		Subscription:          q.Subscription.WithContext(ctx),
		SysUser:               q.SysUser.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
