// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newLessonPackage(db *gorm.DB, opts ...gen.DOOption) lessonPackage {
	_lessonPackage := lessonPackage{}

	_lessonPackage.lessonPackageDo.UseDB(db, opts...)
	_lessonPackage.lessonPackageDo.UseModel(&model.LessonPackage{})

	tableName := _lessonPackage.lessonPackageDo.TableName()
	_lessonPackage.ALL = field.NewAsterisk(tableName)
	_lessonPackage.ID = field.NewInt32(tableName, "id")
	_lessonPackage.OrganizationID = field.NewInt32(tableName, "organization_id")
	_lessonPackage.CampusID = field.NewInt32(tableName, "campus_id")
	_lessonPackage.StudentID = field.NewInt32(tableName, "student_id")
	_lessonPackage.CourseID = field.NewInt32(tableName, "course_id")
	_lessonPackage.TotalLessons = field.NewFloat64(tableName, "total_lessons")
	_lessonPackage.UsedLessons = field.NewFloat64(tableName, "used_lessons")
	_lessonPackage.RemainLessons = field.NewFloat64(tableName, "remain_lessons")
	_lessonPackage.TotalAmount = field.NewFloat64(tableName, "total_amount")
	_lessonPackage.PaidAmount = field.NewFloat64(tableName, "paid_amount")
	_lessonPackage.StartDate = field.NewTime(tableName, "start_date")
	_lessonPackage.EndDate = field.NewTime(tableName, "end_date")
	_lessonPackage.Status = field.NewString(tableName, "status")
	_lessonPackage.LowLessonThreshold = field.NewFloat64(tableName, "low_lesson_threshold")
	_lessonPackage.Remark = field.NewString(tableName, "remark")
	_lessonPackage.CreatedAt = field.NewTime(tableName, "created_at")
	_lessonPackage.UpdatedAt = field.NewTime(tableName, "updated_at")

	_lessonPackage.fillFieldMap()

	return _lessonPackage
}

// lessonPackage 课时包表
type lessonPackage struct {
	lessonPackageDo

	ALL                field.Asterisk
	ID                 field.Int32   // 主键
	OrganizationID     field.Int32   // 所属机构ID
	CampusID           field.Int32   // 所属校区ID
	StudentID          field.Int32   // 学员ID
	CourseID           field.Int32   // 课程ID
	TotalLessons       field.Float64 // 总课时
	UsedLessons        field.Float64 // 已用课时
	RemainLessons      field.Float64 // 剩余课时
	TotalAmount        field.Float64 // 总金额
	PaidAmount         field.Float64 // 已缴金额
	StartDate          field.Time    // 生效日期
	EndDate            field.Time    // 截止日期
	Status             field.String  // 状态：pending/active/exhausted/expired/closed
	LowLessonThreshold field.Float64 // 低课时提醒阈值
	Remark             field.String  // 备注
	CreatedAt          field.Time    // 创建时间
	UpdatedAt          field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (l lessonPackage) Table(newTableName string) *lessonPackage {
	l.lessonPackageDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lessonPackage) As(alias string) *lessonPackage {
	l.lessonPackageDo.DO = *(l.lessonPackageDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lessonPackage) updateTableName(table string) *lessonPackage {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt32(table, "id")
	l.OrganizationID = field.NewInt32(table, "organization_id")
	l.CampusID = field.NewInt32(table, "campus_id")
	l.StudentID = field.NewInt32(table, "student_id")
	l.CourseID = field.NewInt32(table, "course_id")
	l.TotalLessons = field.NewFloat64(table, "total_lessons")
	l.UsedLessons = field.NewFloat64(table, "used_lessons")
	l.RemainLessons = field.NewFloat64(table, "remain_lessons")
	l.TotalAmount = field.NewFloat64(table, "total_amount")
	l.PaidAmount = field.NewFloat64(table, "paid_amount")
	l.StartDate = field.NewTime(table, "start_date")
	l.EndDate = field.NewTime(table, "end_date")
	l.Status = field.NewString(table, "status")
	l.LowLessonThreshold = field.NewFloat64(table, "low_lesson_threshold")
	l.Remark = field.NewString(table, "remark")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *lessonPackage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lessonPackage) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 17)
	l.fieldMap["id"] = l.ID
	l.fieldMap["organization_id"] = l.OrganizationID
	l.fieldMap["campus_id"] = l.CampusID
	l.fieldMap["student_id"] = l.StudentID
	l.fieldMap["course_id"] = l.CourseID
	l.fieldMap["total_lessons"] = l.TotalLessons
	l.fieldMap["used_lessons"] = l.UsedLessons
	l.fieldMap["remain_lessons"] = l.RemainLessons
	l.fieldMap["total_amount"] = l.TotalAmount
	l.fieldMap["paid_amount"] = l.PaidAmount
	l.fieldMap["start_date"] = l.StartDate
	l.fieldMap["end_date"] = l.EndDate
	l.fieldMap["status"] = l.Status
	l.fieldMap["low_lesson_threshold"] = l.LowLessonThreshold
	l.fieldMap["remark"] = l.Remark
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l lessonPackage) clone(db *gorm.DB) lessonPackage {
	l.lessonPackageDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lessonPackage) replaceDB(db *gorm.DB) lessonPackage {
	l.lessonPackageDo.ReplaceDB(db)
	return l
}

type lessonPackageDo struct{ gen.DO }

func (l lessonPackageDo) Debug() *lessonPackageDo {
	return l.withDO(l.DO.Debug())
}

func (l lessonPackageDo) WithContext(ctx context.Context) *lessonPackageDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lessonPackageDo) ReadDB() *lessonPackageDo {
	return l.Clauses(dbresolver.Read)
}

func (l lessonPackageDo) WriteDB() *lessonPackageDo {
	return l.Clauses(dbresolver.Write)
}

func (l lessonPackageDo) Session(config *gorm.Session) *lessonPackageDo {
	return l.withDO(l.DO.Session(config))
}

func (l lessonPackageDo) Clauses(conds ...clause.Expression) *lessonPackageDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lessonPackageDo) Returning(value interface{}, columns ...string) *lessonPackageDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lessonPackageDo) Not(conds ...gen.Condition) *lessonPackageDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lessonPackageDo) Or(conds ...gen.Condition) *lessonPackageDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lessonPackageDo) Select(conds ...field.Expr) *lessonPackageDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lessonPackageDo) Where(conds ...gen.Condition) *lessonPackageDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lessonPackageDo) Order(conds ...field.Expr) *lessonPackageDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lessonPackageDo) Distinct(cols ...field.Expr) *lessonPackageDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lessonPackageDo) Omit(cols ...field.Expr) *lessonPackageDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lessonPackageDo) Join(table schema.Tabler, on ...field.Expr) *lessonPackageDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lessonPackageDo) LeftJoin(table schema.Tabler, on ...field.Expr) *lessonPackageDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lessonPackageDo) RightJoin(table schema.Tabler, on ...field.Expr) *lessonPackageDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lessonPackageDo) Group(cols ...field.Expr) *lessonPackageDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lessonPackageDo) Having(conds ...gen.Condition) *lessonPackageDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lessonPackageDo) Limit(limit int) *lessonPackageDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lessonPackageDo) Offset(offset int) *lessonPackageDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lessonPackageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *lessonPackageDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lessonPackageDo) Unscoped() *lessonPackageDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lessonPackageDo) Create(values ...*model.LessonPackage) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lessonPackageDo) CreateInBatches(values []*model.LessonPackage, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lessonPackageDo) Save(values ...*model.LessonPackage) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lessonPackageDo) First() (*model.LessonPackage, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonPackage), nil
	}
}

func (l lessonPackageDo) Take() (*model.LessonPackage, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonPackage), nil
	}
}

func (l lessonPackageDo) Last() (*model.LessonPackage, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonPackage), nil
	}
}

func (l lessonPackageDo) Find() ([]*model.LessonPackage, error) {
	result, err := l.DO.Find()
	return result.([]*model.LessonPackage), err
}

func (l lessonPackageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LessonPackage, err error) {
	buf := make([]*model.LessonPackage, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lessonPackageDo) FindInBatches(result *[]*model.LessonPackage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lessonPackageDo) Attrs(attrs ...field.AssignExpr) *lessonPackageDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lessonPackageDo) Assign(attrs ...field.AssignExpr) *lessonPackageDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lessonPackageDo) Joins(fields ...field.RelationField) *lessonPackageDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lessonPackageDo) Preload(fields ...field.RelationField) *lessonPackageDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lessonPackageDo) FirstOrInit() (*model.LessonPackage, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonPackage), nil
	}
}

func (l lessonPackageDo) FirstOrCreate() (*model.LessonPackage, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonPackage), nil
	}
}

func (l lessonPackageDo) FindByPage(offset int, limit int) (result []*model.LessonPackage, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lessonPackageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lessonPackageDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lessonPackageDo) Delete(models ...*model.LessonPackage) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lessonPackageDo) withDO(do gen.Dao) *lessonPackageDo {
	l.DO = *do.(*gen.DO)
	return l
}
