// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newLessonRecord(db *gorm.DB, opts ...gen.DOOption) lessonRecord {
	_lessonRecord := lessonRecord{}

	_lessonRecord.lessonRecordDo.UseDB(db, opts...)
	_lessonRecord.lessonRecordDo.UseModel(&model.LessonRecord{})

	tableName := _lessonRecord.lessonRecordDo.TableName()
	_lessonRecord.ALL = field.NewAsterisk(tableName)
	_lessonRecord.ID = field.NewInt32(tableName, "id")
	_lessonRecord.OrganizationID = field.NewInt32(tableName, "organization_id")
	_lessonRecord.CampusID = field.NewInt32(tableName, "campus_id")
	_lessonRecord.ScheduleID = field.NewInt32(tableName, "schedule_id")
	_lessonRecord.StudentID = field.NewInt32(tableName, "student_id")
	_lessonRecord.TeacherID = field.NewInt32(tableName, "teacher_id")
	_lessonRecord.AttendanceStatus = field.NewString(tableName, "attendance_status")
	_lessonRecord.LessonContent = field.NewString(tableName, "lesson_content")
	_lessonRecord.Homework = field.NewString(tableName, "homework")
	_lessonRecord.Feedback = field.NewString(tableName, "feedback")
	_lessonRecord.LessonDeducted = field.NewBool(tableName, "lesson_deducted")
	_lessonRecord.DeductLessonCount = field.NewFloat64(tableName, "deduct_lesson_count")
	_lessonRecord.RecordedAt = field.NewTime(tableName, "recorded_at")
	_lessonRecord.UpdatedAt = field.NewTime(tableName, "updated_at")

	_lessonRecord.fillFieldMap()

	return _lessonRecord
}

// lessonRecord 上课记录表
type lessonRecord struct {
	lessonRecordDo

	ALL               field.Asterisk
	ID                field.Int32   // 主键ID
	OrganizationID    field.Int32   // 所属机构ID
	CampusID          field.Int32   // 所属校区ID
	ScheduleID        field.Int32   // 排课ID
	StudentID         field.Int32   // 学员ID
	TeacherID         field.Int32   // 教师ID
	AttendanceStatus  field.String  // 出勤状态：present/late/absent/leave
	LessonContent     field.String  // 上课内容
	Homework          field.String  // 作业
	Feedback          field.String  // 反馈
	LessonDeducted    field.Bool    // 是否已扣课时：0否1是
	DeductLessonCount field.Float64 // 本次扣减课时数
	RecordedAt        field.Time    // 记录时间
	UpdatedAt         field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (l lessonRecord) Table(newTableName string) *lessonRecord {
	l.lessonRecordDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lessonRecord) As(alias string) *lessonRecord {
	l.lessonRecordDo.DO = *(l.lessonRecordDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lessonRecord) updateTableName(table string) *lessonRecord {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt32(table, "id")
	l.OrganizationID = field.NewInt32(table, "organization_id")
	l.CampusID = field.NewInt32(table, "campus_id")
	l.ScheduleID = field.NewInt32(table, "schedule_id")
	l.StudentID = field.NewInt32(table, "student_id")
	l.TeacherID = field.NewInt32(table, "teacher_id")
	l.AttendanceStatus = field.NewString(table, "attendance_status")
	l.LessonContent = field.NewString(table, "lesson_content")
	l.Homework = field.NewString(table, "homework")
	l.Feedback = field.NewString(table, "feedback")
	l.LessonDeducted = field.NewBool(table, "lesson_deducted")
	l.DeductLessonCount = field.NewFloat64(table, "deduct_lesson_count")
	l.RecordedAt = field.NewTime(table, "recorded_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *lessonRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lessonRecord) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 14)
	l.fieldMap["id"] = l.ID
	l.fieldMap["organization_id"] = l.OrganizationID
	l.fieldMap["campus_id"] = l.CampusID
	l.fieldMap["schedule_id"] = l.ScheduleID
	l.fieldMap["student_id"] = l.StudentID
	l.fieldMap["teacher_id"] = l.TeacherID
	l.fieldMap["attendance_status"] = l.AttendanceStatus
	l.fieldMap["lesson_content"] = l.LessonContent
	l.fieldMap["homework"] = l.Homework
	l.fieldMap["feedback"] = l.Feedback
	l.fieldMap["lesson_deducted"] = l.LessonDeducted
	l.fieldMap["deduct_lesson_count"] = l.DeductLessonCount
	l.fieldMap["recorded_at"] = l.RecordedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l lessonRecord) clone(db *gorm.DB) lessonRecord {
	l.lessonRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lessonRecord) replaceDB(db *gorm.DB) lessonRecord {
	l.lessonRecordDo.ReplaceDB(db)
	return l
}

type lessonRecordDo struct{ gen.DO }

func (l lessonRecordDo) Debug() *lessonRecordDo {
	return l.withDO(l.DO.Debug())
}

func (l lessonRecordDo) WithContext(ctx context.Context) *lessonRecordDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lessonRecordDo) ReadDB() *lessonRecordDo {
	return l.Clauses(dbresolver.Read)
}

func (l lessonRecordDo) WriteDB() *lessonRecordDo {
	return l.Clauses(dbresolver.Write)
}

func (l lessonRecordDo) Session(config *gorm.Session) *lessonRecordDo {
	return l.withDO(l.DO.Session(config))
}

func (l lessonRecordDo) Clauses(conds ...clause.Expression) *lessonRecordDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lessonRecordDo) Returning(value interface{}, columns ...string) *lessonRecordDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lessonRecordDo) Not(conds ...gen.Condition) *lessonRecordDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lessonRecordDo) Or(conds ...gen.Condition) *lessonRecordDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lessonRecordDo) Select(conds ...field.Expr) *lessonRecordDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lessonRecordDo) Where(conds ...gen.Condition) *lessonRecordDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lessonRecordDo) Order(conds ...field.Expr) *lessonRecordDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lessonRecordDo) Distinct(cols ...field.Expr) *lessonRecordDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lessonRecordDo) Omit(cols ...field.Expr) *lessonRecordDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lessonRecordDo) Join(table schema.Tabler, on ...field.Expr) *lessonRecordDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lessonRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *lessonRecordDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lessonRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *lessonRecordDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lessonRecordDo) Group(cols ...field.Expr) *lessonRecordDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lessonRecordDo) Having(conds ...gen.Condition) *lessonRecordDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lessonRecordDo) Limit(limit int) *lessonRecordDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lessonRecordDo) Offset(offset int) *lessonRecordDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lessonRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *lessonRecordDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lessonRecordDo) Unscoped() *lessonRecordDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lessonRecordDo) Create(values ...*model.LessonRecord) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lessonRecordDo) CreateInBatches(values []*model.LessonRecord, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lessonRecordDo) Save(values ...*model.LessonRecord) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lessonRecordDo) First() (*model.LessonRecord, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonRecord), nil
	}
}

func (l lessonRecordDo) Take() (*model.LessonRecord, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonRecord), nil
	}
}

func (l lessonRecordDo) Last() (*model.LessonRecord, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonRecord), nil
	}
}

func (l lessonRecordDo) Find() ([]*model.LessonRecord, error) {
	result, err := l.DO.Find()
	return result.([]*model.LessonRecord), err
}

func (l lessonRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LessonRecord, err error) {
	buf := make([]*model.LessonRecord, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lessonRecordDo) FindInBatches(result *[]*model.LessonRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lessonRecordDo) Attrs(attrs ...field.AssignExpr) *lessonRecordDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lessonRecordDo) Assign(attrs ...field.AssignExpr) *lessonRecordDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lessonRecordDo) Joins(fields ...field.RelationField) *lessonRecordDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lessonRecordDo) Preload(fields ...field.RelationField) *lessonRecordDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lessonRecordDo) FirstOrInit() (*model.LessonRecord, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonRecord), nil
	}
}

func (l lessonRecordDo) FirstOrCreate() (*model.LessonRecord, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LessonRecord), nil
	}
}

func (l lessonRecordDo) FindByPage(offset int, limit int) (result []*model.LessonRecord, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lessonRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lessonRecordDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lessonRecordDo) Delete(models ...*model.LessonRecord) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lessonRecordDo) withDO(do gen.Dao) *lessonRecordDo {
	l.DO = *do.(*gen.DO)
	return l
}
