// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newPaymentRecord(db *gorm.DB, opts ...gen.DOOption) paymentRecord {
	_paymentRecord := paymentRecord{}

	_paymentRecord.paymentRecordDo.UseDB(db, opts...)
	_paymentRecord.paymentRecordDo.UseModel(&model.PaymentRecord{})

	tableName := _paymentRecord.paymentRecordDo.TableName()
	_paymentRecord.ALL = field.NewAsterisk(tableName)
	_paymentRecord.ID = field.NewInt32(tableName, "id")
	_paymentRecord.OrganizationID = field.NewInt32(tableName, "organization_id")
	_paymentRecord.CampusID = field.NewInt32(tableName, "campus_id")
	_paymentRecord.StudentID = field.NewInt32(tableName, "student_id")
	_paymentRecord.LessonPackageID = field.NewInt32(tableName, "lesson_package_id")
	_paymentRecord.PaymentType = field.NewString(tableName, "payment_type")
	_paymentRecord.Amount = field.NewFloat64(tableName, "amount")
	_paymentRecord.PaymentMethod = field.NewString(tableName, "payment_method")
	_paymentRecord.PaymentTime = field.NewTime(tableName, "payment_time")
	_paymentRecord.PaymentStatus = field.NewString(tableName, "payment_status")
	_paymentRecord.Remark = field.NewString(tableName, "remark")
	_paymentRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_paymentRecord.UpdatedAt = field.NewTime(tableName, "updated_at")

	_paymentRecord.fillFieldMap()

	return _paymentRecord
}

// paymentRecord 缴费记录表
type paymentRecord struct {
	paymentRecordDo

	ALL             field.Asterisk
	ID              field.Int32   // 主键
	OrganizationID  field.Int32   // 所属机构ID
	CampusID        field.Int32   // 所属校区ID
	StudentID       field.Int32   // 学员ID
	LessonPackageID field.Int32   // 课时包ID
	PaymentType     field.String  // 缴费类型：signup/renewal
	Amount          field.Float64 // 缴费金额
	PaymentMethod   field.String  // 支付方式：cash/wechat/alipay/bank_transfer/other
	PaymentTime     field.Time    // 缴费时间
	PaymentStatus   field.String  // 状态：paid/pending/partial/refunded
	Remark          field.String  // 备注
	CreatedAt       field.Time    // 创建时间
	UpdatedAt       field.Time    // 更新时间

	fieldMap map[string]field.Expr
}

func (p paymentRecord) Table(newTableName string) *paymentRecord {
	p.paymentRecordDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p paymentRecord) As(alias string) *paymentRecord {
	p.paymentRecordDo.DO = *(p.paymentRecordDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *paymentRecord) updateTableName(table string) *paymentRecord {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.OrganizationID = field.NewInt32(table, "organization_id")
	p.CampusID = field.NewInt32(table, "campus_id")
	p.StudentID = field.NewInt32(table, "student_id")
	p.LessonPackageID = field.NewInt32(table, "lesson_package_id")
	p.PaymentType = field.NewString(table, "payment_type")
	p.Amount = field.NewFloat64(table, "amount")
	p.PaymentMethod = field.NewString(table, "payment_method")
	p.PaymentTime = field.NewTime(table, "payment_time")
	p.PaymentStatus = field.NewString(table, "payment_status")
	p.Remark = field.NewString(table, "remark")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *paymentRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *paymentRecord) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["organization_id"] = p.OrganizationID
	p.fieldMap["campus_id"] = p.CampusID
	p.fieldMap["student_id"] = p.StudentID
	p.fieldMap["lesson_package_id"] = p.LessonPackageID
	p.fieldMap["payment_type"] = p.PaymentType
	p.fieldMap["amount"] = p.Amount
	p.fieldMap["payment_method"] = p.PaymentMethod
	p.fieldMap["payment_time"] = p.PaymentTime
	p.fieldMap["payment_status"] = p.PaymentStatus
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p paymentRecord) clone(db *gorm.DB) paymentRecord {
	p.paymentRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p paymentRecord) replaceDB(db *gorm.DB) paymentRecord {
	p.paymentRecordDo.ReplaceDB(db)
	return p
}

type paymentRecordDo struct{ gen.DO }

func (p paymentRecordDo) Debug() *paymentRecordDo {
	return p.withDO(p.DO.Debug())
}

func (p paymentRecordDo) WithContext(ctx context.Context) *paymentRecordDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p paymentRecordDo) ReadDB() *paymentRecordDo {
	return p.Clauses(dbresolver.Read)
}

func (p paymentRecordDo) WriteDB() *paymentRecordDo {
	return p.Clauses(dbresolver.Write)
}

func (p paymentRecordDo) Session(config *gorm.Session) *paymentRecordDo {
	return p.withDO(p.DO.Session(config))
}

func (p paymentRecordDo) Clauses(conds ...clause.Expression) *paymentRecordDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p paymentRecordDo) Returning(value interface{}, columns ...string) *paymentRecordDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p paymentRecordDo) Not(conds ...gen.Condition) *paymentRecordDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p paymentRecordDo) Or(conds ...gen.Condition) *paymentRecordDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p paymentRecordDo) Select(conds ...field.Expr) *paymentRecordDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p paymentRecordDo) Where(conds ...gen.Condition) *paymentRecordDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p paymentRecordDo) Order(conds ...field.Expr) *paymentRecordDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p paymentRecordDo) Distinct(cols ...field.Expr) *paymentRecordDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p paymentRecordDo) Omit(cols ...field.Expr) *paymentRecordDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p paymentRecordDo) Join(table schema.Tabler, on ...field.Expr) *paymentRecordDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p paymentRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *paymentRecordDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p paymentRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *paymentRecordDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p paymentRecordDo) Group(cols ...field.Expr) *paymentRecordDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p paymentRecordDo) Having(conds ...gen.Condition) *paymentRecordDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p paymentRecordDo) Limit(limit int) *paymentRecordDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p paymentRecordDo) Offset(offset int) *paymentRecordDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p paymentRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *paymentRecordDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p paymentRecordDo) Unscoped() *paymentRecordDo {
	return p.withDO(p.DO.Unscoped())
}

func (p paymentRecordDo) Create(values ...*model.PaymentRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p paymentRecordDo) CreateInBatches(values []*model.PaymentRecord, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p paymentRecordDo) Save(values ...*model.PaymentRecord) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p paymentRecordDo) First() (*model.PaymentRecord, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRecord), nil
	}
}

func (p paymentRecordDo) Take() (*model.PaymentRecord, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRecord), nil
	}
}

func (p paymentRecordDo) Last() (*model.PaymentRecord, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRecord), nil
	}
}

func (p paymentRecordDo) Find() ([]*model.PaymentRecord, error) {
	result, err := p.DO.Find()
	return result.([]*model.PaymentRecord), err
}

func (p paymentRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PaymentRecord, err error) {
	buf := make([]*model.PaymentRecord, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p paymentRecordDo) FindInBatches(result *[]*model.PaymentRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p paymentRecordDo) Attrs(attrs ...field.AssignExpr) *paymentRecordDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p paymentRecordDo) Assign(attrs ...field.AssignExpr) *paymentRecordDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p paymentRecordDo) Joins(fields ...field.RelationField) *paymentRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p paymentRecordDo) Preload(fields ...field.RelationField) *paymentRecordDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p paymentRecordDo) FirstOrInit() (*model.PaymentRecord, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRecord), nil
	}
}

func (p paymentRecordDo) FirstOrCreate() (*model.PaymentRecord, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PaymentRecord), nil
	}
}

func (p paymentRecordDo) FindByPage(offset int, limit int) (result []*model.PaymentRecord, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p paymentRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p paymentRecordDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p paymentRecordDo) Delete(models ...*model.PaymentRecord) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *paymentRecordDo) withDO(do gen.Dao) *paymentRecordDo {
	p.DO = *do.(*gen.DO)
	return p
}
