// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newRescheduleRecord(db *gorm.DB, opts ...gen.DOOption) rescheduleRecord {
	_rescheduleRecord := rescheduleRecord{}

	_rescheduleRecord.rescheduleRecordDo.UseDB(db, opts...)
	_rescheduleRecord.rescheduleRecordDo.UseModel(&model.RescheduleRecord{})

	tableName := _rescheduleRecord.rescheduleRecordDo.TableName()
	_rescheduleRecord.ALL = field.NewAsterisk(tableName)
	_rescheduleRecord.ID = field.NewInt32(tableName, "id")
	_rescheduleRecord.OrganizationID = field.NewInt32(tableName, "organization_id")
	_rescheduleRecord.CampusID = field.NewInt32(tableName, "campus_id")
	_rescheduleRecord.OldScheduleID = field.NewInt32(tableName, "old_schedule_id")
	_rescheduleRecord.NewScheduleID = field.NewInt32(tableName, "new_schedule_id")
	_rescheduleRecord.OperationType = field.NewString(tableName, "operation_type")
	_rescheduleRecord.Reason = field.NewString(tableName, "reason")
	_rescheduleRecord.OperatorID = field.NewInt32(tableName, "operator_id")
	_rescheduleRecord.CreatedAt = field.NewTime(tableName, "created_at")

	_rescheduleRecord.fillFieldMap()

	return _rescheduleRecord
}

// rescheduleRecord 调补课记录表
type rescheduleRecord struct {
	rescheduleRecordDo

	ALL            field.Asterisk
	ID             field.Int32  // 主键
	OrganizationID field.Int32  // 所属机构ID
	CampusID       field.Int32  // 所属校区ID
	OldScheduleID  field.Int32  // 原排课ID
	NewScheduleID  field.Int32  // 新排课ID
	OperationType  field.String // 类型：leave/reschedule/makeup/cancel
	Reason         field.String // 原因
	OperatorID     field.Int32  // 操作人
	CreatedAt      field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (r rescheduleRecord) Table(newTableName string) *rescheduleRecord {
	r.rescheduleRecordDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rescheduleRecord) As(alias string) *rescheduleRecord {
	r.rescheduleRecordDo.DO = *(r.rescheduleRecordDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rescheduleRecord) updateTableName(table string) *rescheduleRecord {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.OrganizationID = field.NewInt32(table, "organization_id")
	r.CampusID = field.NewInt32(table, "campus_id")
	r.OldScheduleID = field.NewInt32(table, "old_schedule_id")
	r.NewScheduleID = field.NewInt32(table, "new_schedule_id")
	r.OperationType = field.NewString(table, "operation_type")
	r.Reason = field.NewString(table, "reason")
	r.OperatorID = field.NewInt32(table, "operator_id")
	r.CreatedAt = field.NewTime(table, "created_at")

	r.fillFieldMap()

	return r
}

func (r *rescheduleRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rescheduleRecord) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 9)
	r.fieldMap["id"] = r.ID
	r.fieldMap["organization_id"] = r.OrganizationID
	r.fieldMap["campus_id"] = r.CampusID
	r.fieldMap["old_schedule_id"] = r.OldScheduleID
	r.fieldMap["new_schedule_id"] = r.NewScheduleID
	r.fieldMap["operation_type"] = r.OperationType
	r.fieldMap["reason"] = r.Reason
	r.fieldMap["operator_id"] = r.OperatorID
	r.fieldMap["created_at"] = r.CreatedAt
}

func (r rescheduleRecord) clone(db *gorm.DB) rescheduleRecord {
	r.rescheduleRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rescheduleRecord) replaceDB(db *gorm.DB) rescheduleRecord {
	r.rescheduleRecordDo.ReplaceDB(db)
	return r
}

type rescheduleRecordDo struct{ gen.DO }

func (r rescheduleRecordDo) Debug() *rescheduleRecordDo {
	return r.withDO(r.DO.Debug())
}

func (r rescheduleRecordDo) WithContext(ctx context.Context) *rescheduleRecordDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rescheduleRecordDo) ReadDB() *rescheduleRecordDo {
	return r.Clauses(dbresolver.Read)
}

func (r rescheduleRecordDo) WriteDB() *rescheduleRecordDo {
	return r.Clauses(dbresolver.Write)
}

func (r rescheduleRecordDo) Session(config *gorm.Session) *rescheduleRecordDo {
	return r.withDO(r.DO.Session(config))
}

func (r rescheduleRecordDo) Clauses(conds ...clause.Expression) *rescheduleRecordDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rescheduleRecordDo) Returning(value interface{}, columns ...string) *rescheduleRecordDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rescheduleRecordDo) Not(conds ...gen.Condition) *rescheduleRecordDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rescheduleRecordDo) Or(conds ...gen.Condition) *rescheduleRecordDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rescheduleRecordDo) Select(conds ...field.Expr) *rescheduleRecordDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rescheduleRecordDo) Where(conds ...gen.Condition) *rescheduleRecordDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rescheduleRecordDo) Order(conds ...field.Expr) *rescheduleRecordDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rescheduleRecordDo) Distinct(cols ...field.Expr) *rescheduleRecordDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rescheduleRecordDo) Omit(cols ...field.Expr) *rescheduleRecordDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rescheduleRecordDo) Join(table schema.Tabler, on ...field.Expr) *rescheduleRecordDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rescheduleRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *rescheduleRecordDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rescheduleRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) *rescheduleRecordDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rescheduleRecordDo) Group(cols ...field.Expr) *rescheduleRecordDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rescheduleRecordDo) Having(conds ...gen.Condition) *rescheduleRecordDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rescheduleRecordDo) Limit(limit int) *rescheduleRecordDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rescheduleRecordDo) Offset(offset int) *rescheduleRecordDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rescheduleRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *rescheduleRecordDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rescheduleRecordDo) Unscoped() *rescheduleRecordDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rescheduleRecordDo) Create(values ...*model.RescheduleRecord) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rescheduleRecordDo) CreateInBatches(values []*model.RescheduleRecord, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rescheduleRecordDo) Save(values ...*model.RescheduleRecord) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rescheduleRecordDo) First() (*model.RescheduleRecord, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RescheduleRecord), nil
	}
}

func (r rescheduleRecordDo) Take() (*model.RescheduleRecord, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RescheduleRecord), nil
	}
}

func (r rescheduleRecordDo) Last() (*model.RescheduleRecord, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RescheduleRecord), nil
	}
}

func (r rescheduleRecordDo) Find() ([]*model.RescheduleRecord, error) {
	result, err := r.DO.Find()
	return result.([]*model.RescheduleRecord), err
}

func (r rescheduleRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RescheduleRecord, err error) {
	buf := make([]*model.RescheduleRecord, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rescheduleRecordDo) FindInBatches(result *[]*model.RescheduleRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rescheduleRecordDo) Attrs(attrs ...field.AssignExpr) *rescheduleRecordDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rescheduleRecordDo) Assign(attrs ...field.AssignExpr) *rescheduleRecordDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rescheduleRecordDo) Joins(fields ...field.RelationField) *rescheduleRecordDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rescheduleRecordDo) Preload(fields ...field.RelationField) *rescheduleRecordDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rescheduleRecordDo) FirstOrInit() (*model.RescheduleRecord, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RescheduleRecord), nil
	}
}

func (r rescheduleRecordDo) FirstOrCreate() (*model.RescheduleRecord, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RescheduleRecord), nil
	}
}

func (r rescheduleRecordDo) FindByPage(offset int, limit int) (result []*model.RescheduleRecord, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rescheduleRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rescheduleRecordDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rescheduleRecordDo) Delete(models ...*model.RescheduleRecord) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rescheduleRecordDo) withDO(do gen.Dao) *rescheduleRecordDo {
	r.DO = *do.(*gen.DO)
	return r
}
