// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newSchemaMigrations(db *gorm.DB, opts ...gen.DOOption) schemaMigrations {
	_schemaMigrations := schemaMigrations{}

	_schemaMigrations.schemaMigrationsDo.UseDB(db, opts...)
	_schemaMigrations.schemaMigrationsDo.UseModel(&model.SchemaMigrations{})

	tableName := _schemaMigrations.schemaMigrationsDo.TableName()
	_schemaMigrations.ALL = field.NewAsterisk(tableName)
	_schemaMigrations.Version = field.NewString(tableName, "version")
	_schemaMigrations.Checksum = field.NewString(tableName, "checksum")
	_schemaMigrations.RollbackPolicy = field.NewString(tableName, "rollback_policy")
	_schemaMigrations.AppliedAt = field.NewTime(tableName, "applied_at")

	_schemaMigrations.fillFieldMap()

	return _schemaMigrations
}

// schemaMigrations schema migrations
type schemaMigrations struct {
	schemaMigrationsDo

	ALL            field.Asterisk
	Version        field.String
	Checksum       field.String
	RollbackPolicy field.String
	AppliedAt      field.Time

	fieldMap map[string]field.Expr
}

func (s schemaMigrations) Table(newTableName string) *schemaMigrations {
	s.schemaMigrationsDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s schemaMigrations) As(alias string) *schemaMigrations {
	s.schemaMigrationsDo.DO = *(s.schemaMigrationsDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *schemaMigrations) updateTableName(table string) *schemaMigrations {
	s.ALL = field.NewAsterisk(table)
	s.Version = field.NewString(table, "version")
	s.Checksum = field.NewString(table, "checksum")
	s.RollbackPolicy = field.NewString(table, "rollback_policy")
	s.AppliedAt = field.NewTime(table, "applied_at")

	s.fillFieldMap()

	return s
}

func (s *schemaMigrations) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *schemaMigrations) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["version"] = s.Version
	s.fieldMap["checksum"] = s.Checksum
	s.fieldMap["rollback_policy"] = s.RollbackPolicy
	s.fieldMap["applied_at"] = s.AppliedAt
}

func (s schemaMigrations) clone(db *gorm.DB) schemaMigrations {
	s.schemaMigrationsDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s schemaMigrations) replaceDB(db *gorm.DB) schemaMigrations {
	s.schemaMigrationsDo.ReplaceDB(db)
	return s
}

type schemaMigrationsDo struct{ gen.DO }

func (s schemaMigrationsDo) Debug() *schemaMigrationsDo {
	return s.withDO(s.DO.Debug())
}

func (s schemaMigrationsDo) WithContext(ctx context.Context) *schemaMigrationsDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s schemaMigrationsDo) ReadDB() *schemaMigrationsDo {
	return s.Clauses(dbresolver.Read)
}

func (s schemaMigrationsDo) WriteDB() *schemaMigrationsDo {
	return s.Clauses(dbresolver.Write)
}

func (s schemaMigrationsDo) Session(config *gorm.Session) *schemaMigrationsDo {
	return s.withDO(s.DO.Session(config))
}

func (s schemaMigrationsDo) Clauses(conds ...clause.Expression) *schemaMigrationsDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s schemaMigrationsDo) Returning(value interface{}, columns ...string) *schemaMigrationsDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s schemaMigrationsDo) Not(conds ...gen.Condition) *schemaMigrationsDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s schemaMigrationsDo) Or(conds ...gen.Condition) *schemaMigrationsDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s schemaMigrationsDo) Select(conds ...field.Expr) *schemaMigrationsDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s schemaMigrationsDo) Where(conds ...gen.Condition) *schemaMigrationsDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s schemaMigrationsDo) Order(conds ...field.Expr) *schemaMigrationsDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s schemaMigrationsDo) Distinct(cols ...field.Expr) *schemaMigrationsDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s schemaMigrationsDo) Omit(cols ...field.Expr) *schemaMigrationsDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s schemaMigrationsDo) Join(table schema.Tabler, on ...field.Expr) *schemaMigrationsDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s schemaMigrationsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *schemaMigrationsDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s schemaMigrationsDo) RightJoin(table schema.Tabler, on ...field.Expr) *schemaMigrationsDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s schemaMigrationsDo) Group(cols ...field.Expr) *schemaMigrationsDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s schemaMigrationsDo) Having(conds ...gen.Condition) *schemaMigrationsDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s schemaMigrationsDo) Limit(limit int) *schemaMigrationsDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s schemaMigrationsDo) Offset(offset int) *schemaMigrationsDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s schemaMigrationsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *schemaMigrationsDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s schemaMigrationsDo) Unscoped() *schemaMigrationsDo {
	return s.withDO(s.DO.Unscoped())
}

func (s schemaMigrationsDo) Create(values ...*model.SchemaMigrations) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s schemaMigrationsDo) CreateInBatches(values []*model.SchemaMigrations, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s schemaMigrationsDo) Save(values ...*model.SchemaMigrations) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s schemaMigrationsDo) First() (*model.SchemaMigrations, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SchemaMigrations), nil
	}
}

func (s schemaMigrationsDo) Take() (*model.SchemaMigrations, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SchemaMigrations), nil
	}
}

func (s schemaMigrationsDo) Last() (*model.SchemaMigrations, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SchemaMigrations), nil
	}
}

func (s schemaMigrationsDo) Find() ([]*model.SchemaMigrations, error) {
	result, err := s.DO.Find()
	return result.([]*model.SchemaMigrations), err
}

func (s schemaMigrationsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SchemaMigrations, err error) {
	buf := make([]*model.SchemaMigrations, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s schemaMigrationsDo) FindInBatches(result *[]*model.SchemaMigrations, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s schemaMigrationsDo) Attrs(attrs ...field.AssignExpr) *schemaMigrationsDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s schemaMigrationsDo) Assign(attrs ...field.AssignExpr) *schemaMigrationsDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s schemaMigrationsDo) Joins(fields ...field.RelationField) *schemaMigrationsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s schemaMigrationsDo) Preload(fields ...field.RelationField) *schemaMigrationsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s schemaMigrationsDo) FirstOrInit() (*model.SchemaMigrations, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SchemaMigrations), nil
	}
}

func (s schemaMigrationsDo) FirstOrCreate() (*model.SchemaMigrations, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SchemaMigrations), nil
	}
}

func (s schemaMigrationsDo) FindByPage(offset int, limit int) (result []*model.SchemaMigrations, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s schemaMigrationsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s schemaMigrationsDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s schemaMigrationsDo) Delete(models ...*model.SchemaMigrations) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *schemaMigrationsDo) withDO(do gen.Dao) *schemaMigrationsDo {
	s.DO = *do.(*gen.DO)
	return s
}
