// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"edu-schedule-system/internal/repository/mysql/model"
)

func newSchedule(db *gorm.DB, opts ...gen.DOOption) schedule {
	_schedule := schedule{}

	_schedule.scheduleDo.UseDB(db, opts...)
	_schedule.scheduleDo.UseModel(&model.Schedule{})

	tableName := _schedule.scheduleDo.TableName()
	_schedule.ALL = field.NewAsterisk(tableName)
	_schedule.ID = field.NewInt32(tableName, "id")
	_schedule.OrganizationID = field.NewInt32(tableName, "organization_id")
	_schedule.CampusID = field.NewInt32(tableName, "campus_id")
	_schedule.StudentID = field.NewInt32(tableName, "student_id")
	_schedule.CourseID = field.NewInt32(tableName, "course_id")
	_schedule.TeacherID = field.NewInt32(tableName, "teacher_id")
	_schedule.LessonPackageID = field.NewInt32(tableName, "lesson_package_id")
	_schedule.ClassDate = field.NewTime(tableName, "class_date")
	_schedule.StartTime = field.NewTime(tableName, "start_time")
	_schedule.EndTime = field.NewTime(tableName, "end_time")
	_schedule.Classroom = field.NewString(tableName, "classroom")
	_schedule.ScheduleStatus = field.NewString(tableName, "schedule_status")
	_schedule.OriginalScheduleID = field.NewInt32(tableName, "original_schedule_id")
	_schedule.IsMakeup = field.NewBool(tableName, "is_makeup")
	_schedule.Remark = field.NewString(tableName, "remark")
	_schedule.CreatedAt = field.NewTime(tableName, "created_at")
	_schedule.UpdatedAt = field.NewTime(tableName, "updated_at")

	_schedule.fillFieldMap()

	return _schedule
}

// schedule 排课表
type schedule struct {
	scheduleDo

	ALL                field.Asterisk
	ID                 field.Int32  // 主键
	OrganizationID     field.Int32  // 所属机构ID
	CampusID           field.Int32  // 所属校区ID
	StudentID          field.Int32  // 学员ID
	CourseID           field.Int32  // 课程ID
	TeacherID          field.Int32  // 教师ID
	LessonPackageID    field.Int32  // 关联课时包ID
	ClassDate          field.Time   // 上课日期
	StartTime          field.Time   // 开始时间
	EndTime            field.Time   // 结束时间
	Classroom          field.String // 教室/地点
	ScheduleStatus     field.String // 状态：scheduled/completed/leave/rescheduled/cancelled/makeup_pending
	OriginalScheduleID field.Int32  // 原始课程ID
	IsMakeup           field.Bool   // 是否补课：0否1是
	Remark             field.String // 备注
	CreatedAt          field.Time   // 创建时间
	UpdatedAt          field.Time   // 更新时间

	fieldMap map[string]field.Expr
}

func (s schedule) Table(newTableName string) *schedule {
	s.scheduleDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s schedule) As(alias string) *schedule {
	s.scheduleDo.DO = *(s.scheduleDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *schedule) updateTableName(table string) *schedule {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.OrganizationID = field.NewInt32(table, "organization_id")
	s.CampusID = field.NewInt32(table, "campus_id")
	s.StudentID = field.NewInt32(table, "student_id")
	s.CourseID = field.NewInt32(table, "course_id")
	s.TeacherID = field.NewInt32(table, "teacher_id")
	s.LessonPackageID = field.NewInt32(table, "lesson_package_id")
	s.ClassDate = field.NewTime(table, "class_date")
	s.StartTime = field.NewTime(table, "start_time")
	s.EndTime = field.NewTime(table, "end_time")
	s.Classroom = field.NewString(table, "classroom")
	s.ScheduleStatus = field.NewString(table, "schedule_status")
	s.OriginalScheduleID = field.NewInt32(table, "original_schedule_id")
	s.IsMakeup = field.NewBool(table, "is_makeup")
	s.Remark = field.NewString(table, "remark")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *schedule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *schedule) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 17)
	s.fieldMap["id"] = s.ID
	s.fieldMap["organization_id"] = s.OrganizationID
	s.fieldMap["campus_id"] = s.CampusID
	s.fieldMap["student_id"] = s.StudentID
	s.fieldMap["course_id"] = s.CourseID
	s.fieldMap["teacher_id"] = s.TeacherID
	s.fieldMap["lesson_package_id"] = s.LessonPackageID
	s.fieldMap["class_date"] = s.ClassDate
	s.fieldMap["start_time"] = s.StartTime
	s.fieldMap["end_time"] = s.EndTime
	s.fieldMap["classroom"] = s.Classroom
	s.fieldMap["schedule_status"] = s.ScheduleStatus
	s.fieldMap["original_schedule_id"] = s.OriginalScheduleID
	s.fieldMap["is_makeup"] = s.IsMakeup
	s.fieldMap["remark"] = s.Remark
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s schedule) clone(db *gorm.DB) schedule {
	s.scheduleDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s schedule) replaceDB(db *gorm.DB) schedule {
	s.scheduleDo.ReplaceDB(db)
	return s
}

type scheduleDo struct{ gen.DO }

func (s scheduleDo) Debug() *scheduleDo {
	return s.withDO(s.DO.Debug())
}

func (s scheduleDo) WithContext(ctx context.Context) *scheduleDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s scheduleDo) ReadDB() *scheduleDo {
	return s.Clauses(dbresolver.Read)
}

func (s scheduleDo) WriteDB() *scheduleDo {
	return s.Clauses(dbresolver.Write)
}

func (s scheduleDo) Session(config *gorm.Session) *scheduleDo {
	return s.withDO(s.DO.Session(config))
}

func (s scheduleDo) Clauses(conds ...clause.Expression) *scheduleDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s scheduleDo) Returning(value interface{}, columns ...string) *scheduleDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s scheduleDo) Not(conds ...gen.Condition) *scheduleDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s scheduleDo) Or(conds ...gen.Condition) *scheduleDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s scheduleDo) Select(conds ...field.Expr) *scheduleDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s scheduleDo) Where(conds ...gen.Condition) *scheduleDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s scheduleDo) Order(conds ...field.Expr) *scheduleDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s scheduleDo) Distinct(cols ...field.Expr) *scheduleDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s scheduleDo) Omit(cols ...field.Expr) *scheduleDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s scheduleDo) Join(table schema.Tabler, on ...field.Expr) *scheduleDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s scheduleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *scheduleDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s scheduleDo) RightJoin(table schema.Tabler, on ...field.Expr) *scheduleDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s scheduleDo) Group(cols ...field.Expr) *scheduleDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s scheduleDo) Having(conds ...gen.Condition) *scheduleDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s scheduleDo) Limit(limit int) *scheduleDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s scheduleDo) Offset(offset int) *scheduleDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s scheduleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *scheduleDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s scheduleDo) Unscoped() *scheduleDo {
	return s.withDO(s.DO.Unscoped())
}

func (s scheduleDo) Create(values ...*model.Schedule) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s scheduleDo) CreateInBatches(values []*model.Schedule, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s scheduleDo) Save(values ...*model.Schedule) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s scheduleDo) First() (*model.Schedule, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Schedule), nil
	}
}

func (s scheduleDo) Take() (*model.Schedule, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Schedule), nil
	}
}

func (s scheduleDo) Last() (*model.Schedule, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Schedule), nil
	}
}

func (s scheduleDo) Find() ([]*model.Schedule, error) {
	result, err := s.DO.Find()
	return result.([]*model.Schedule), err
}

func (s scheduleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Schedule, err error) {
	buf := make([]*model.Schedule, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s scheduleDo) FindInBatches(result *[]*model.Schedule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s scheduleDo) Attrs(attrs ...field.AssignExpr) *scheduleDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s scheduleDo) Assign(attrs ...field.AssignExpr) *scheduleDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s scheduleDo) Joins(fields ...field.RelationField) *scheduleDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s scheduleDo) Preload(fields ...field.RelationField) *scheduleDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s scheduleDo) FirstOrInit() (*model.Schedule, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Schedule), nil
	}
}

func (s scheduleDo) FirstOrCreate() (*model.Schedule, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Schedule), nil
	}
}

func (s scheduleDo) FindByPage(offset int, limit int) (result []*model.Schedule, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s scheduleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s scheduleDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s scheduleDo) Delete(models ...*model.Schedule) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *scheduleDo) withDO(do gen.Dao) *scheduleDo {
	s.DO = *do.(*gen.DO)
	return s
}
