// Code generated by cmd/handlergen. DO NOT EDIT.

package lesson_package

import (
	"edu-schedule-system/internal/pkg/core"
)

func RegisterGeneratedLessonPackageRoutes(h *Handler, r core.RouterGroup) {
	// 新增数据
	r.POST("/lesson_package", h.Create())

	// 获取列表数据
	r.GET("/lesson_packages", h.List())

	// 根据 ID 获取数据
	r.GET("/lesson_package/:id", h.GetByID())

	// 根据 ID 更新数据
	r.PUT("/lesson_package/:id", h.UpdateByID())

	// 根据 ID 删除数据
	r.DELETE("/lesson_package/:id", h.DeleteByID())
}
