// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthSession = "auth_session"

// AuthSession 认证会话表
type AuthSession struct {
	ID                 string     `gorm:"column:id;type:varchar(64);primaryKey;comment:会话ID" json:"id"`                                           // 会话ID
	UserID             int32      `gorm:"column:user_id;type:int unsigned;not null;comment:用户ID" json:"user_id"`                                  // 用户ID
	OrganizationID     *int32     `gorm:"column:organization_id;type:int unsigned;comment:所属机构ID快照" json:"organization_id"`                       // 所属机构ID快照
	CampusID           *int32     `gorm:"column:campus_id;type:int unsigned;comment:所属校区ID快照" json:"campus_id"`                                   // 所属校区ID快照
	RoleCode           string     `gorm:"column:role_code;type:varchar(32);not null;comment:角色编码快照" json:"role_code"`                             // 角色编码快照
	DeviceID           string     `gorm:"column:device_id;type:varchar(64);not null;comment:设备指纹ID" json:"device_id"`                             // 设备指纹ID
	DeviceName         string     `gorm:"column:device_name;type:varchar(120);not null;comment:设备名称" json:"device_name"`                          // 设备名称
	ClientIP           string     `gorm:"column:client_ip;type:varchar(64);not null;comment:登录/刷新IP" json:"client_ip"`                            // 登录/刷新IP
	UserAgent          string     `gorm:"column:user_agent;type:varchar(255);not null;comment:客户端UA" json:"user_agent"`                           // 客户端UA
	UserAgentHash      string     `gorm:"column:user_agent_hash;type:varchar(64);not null;comment:UA哈希" json:"user_agent_hash"`                   // UA哈希
	AccessTokenID      string     `gorm:"column:access_token_id;type:varchar(128);not null;comment:当前 access token id" json:"access_token_id"`    // 当前 access token id
	RefreshTokenID     string     `gorm:"column:refresh_token_id;type:varchar(128);not null;comment:当前 refresh token id" json:"refresh_token_id"` // 当前 refresh token id
	RefreshTokenHash   string     `gorm:"column:refresh_token_hash;type:varchar(64);not null;comment:refresh token 摘要" json:"refresh_token_hash"` // refresh token 摘要
	Status             string     `gorm:"column:status;type:varchar(20);not null;default:active;comment:active/revoked" json:"status"`            // active/revoked
	IsSuspicious       bool       `gorm:"column:is_suspicious;type:tinyint(1);not null;comment:是否异常会话" json:"is_suspicious"`                      // 是否异常会话
	RiskFlags          *string    `gorm:"column:risk_flags;type:json;comment:风险标签" json:"risk_flags"`                                             // 风险标签
	LastSeenAt         *time.Time `gorm:"column:last_seen_at;type:timestamp;comment:最近活跃时间" json:"last_seen_at"`                                  // 最近活跃时间
	LastRefreshedAt    *time.Time `gorm:"column:last_refreshed_at;type:timestamp;comment:最近刷新时间" json:"last_refreshed_at"`                        // 最近刷新时间
	RevokedAt          *time.Time `gorm:"column:revoked_at;type:timestamp;comment:撤销时间" json:"revoked_at"`                                        // 撤销时间
	RevokedReason      string     `gorm:"column:revoked_reason;type:varchar(64);not null;comment:撤销原因" json:"revoked_reason"`                     // 撤销原因
	RecoveryVerifiedAt *time.Time `gorm:"column:recovery_verified_at;type:timestamp;comment:因恢复流程被校验的时间" json:"recovery_verified_at"`             // 因恢复流程被校验的时间
	CreatedAt          time.Time  `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`     // 创建时间
	UpdatedAt          time.Time  `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`     // 更新时间
}

// TableName AuthSession's table name
func (*AuthSession) TableName() string {
	return TableNameAuthSession
}
