// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthRecoveryAudit = "auth_recovery_audit"

// AuthRecoveryAudit 账户恢复审计表
type AuthRecoveryAudit struct {
	ID          string    `gorm:"column:id;type:varchar(64);primaryKey;comment:审计ID" json:"id"`                                       // 审计ID
	ChallengeID string    `gorm:"column:challenge_id;type:varchar(64);not null;comment:恢复挑战ID" json:"challenge_id"`                   // 恢复挑战ID
	UserID      int32     `gorm:"column:user_id;type:int unsigned;not null;comment:用户ID" json:"user_id"`                              // 用户ID
	Action      string    `gorm:"column:action;type:varchar(64);not null;comment:动作" json:"action"`                                   // 动作
	Status      string    `gorm:"column:status;type:varchar(20);not null;comment:状态" json:"status"`                                   // 状态
	Detail      *string   `gorm:"column:detail;type:text;comment:详情" json:"detail"`                                                   // 详情
	ActorIP     string    `gorm:"column:actor_ip;type:varchar(64);not null;comment:操作者IP" json:"actor_ip"`                            // 操作者IP
	UserAgent   string    `gorm:"column:user_agent;type:varchar(255);not null;comment:操作者UA" json:"user_agent"`                       // 操作者UA
	CreatedAt   time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName AuthRecoveryAudit's table name
func (*AuthRecoveryAudit) TableName() string {
	return TableNameAuthRecoveryAudit
}
