// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAuthRecoveryChallenge = "auth_recovery_challenge"

// AuthRecoveryChallenge 账户恢复挑战表
type AuthRecoveryChallenge struct {
	ID                  string     `gorm:"column:id;type:varchar(64);primaryKey;comment:恢复挑战ID" json:"id"`                                                  // 恢复挑战ID
	UserID              int32      `gorm:"column:user_id;type:int unsigned;not null;comment:用户ID" json:"user_id"`                                           // 用户ID
	Username            string     `gorm:"column:username;type:varchar(50);not null;comment:用户名快照" json:"username"`                                         // 用户名快照
	Channel             string     `gorm:"column:channel;type:varchar(20);not null;comment:主验证通道 email/sms" json:"channel"`                                 // 主验证通道 email/sms
	ChannelTarget       string     `gorm:"column:channel_target;type:varchar(120);not null;comment:主验证目标" json:"channel_target"`                            // 主验证目标
	CodeHash            string     `gorm:"column:code_hash;type:varchar(64);not null;comment:主验证码摘要" json:"code_hash"`                                      // 主验证码摘要
	SecondChannel       string     `gorm:"column:second_channel;type:varchar(20);not null;comment:二次验证通道" json:"second_channel"`                            // 二次验证通道
	SecondChannelTarget string     `gorm:"column:second_channel_target;type:varchar(120);not null;comment:二次验证目标" json:"second_channel_target"`             // 二次验证目标
	SecondCodeHash      string     `gorm:"column:second_code_hash;type:varchar(64);not null;comment:二次验证码摘要" json:"second_code_hash"`                       // 二次验证码摘要
	Status              string     `gorm:"column:status;type:varchar(20);not null;default:pending;comment:pending/verified/consumed/expired" json:"status"` // pending/verified/consumed/expired
	RiskFlags           *string    `gorm:"column:risk_flags;type:json;comment:恢复风险标签" json:"risk_flags"`                                                    // 恢复风险标签
	RequestedIP         string     `gorm:"column:requested_ip;type:varchar(64);not null;comment:请求IP" json:"requested_ip"`                                  // 请求IP
	RequestedUserAgent  string     `gorm:"column:requested_user_agent;type:varchar(255);not null;comment:请求UA" json:"requested_user_agent"`                 // 请求UA
	ExpiresAt           time.Time  `gorm:"column:expires_at;type:timestamp;not null;comment:过期时间" json:"expires_at"`                                        // 过期时间
	VerifiedAt          *time.Time `gorm:"column:verified_at;type:timestamp;comment:验证完成时间" json:"verified_at"`                                             // 验证完成时间
	ConsumedAt          *time.Time `gorm:"column:consumed_at;type:timestamp;comment:消费时间" json:"consumed_at"`                                               // 消费时间
	CreatedAt           time.Time  `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`              // 创建时间
	UpdatedAt           time.Time  `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`              // 更新时间
}

// TableName AuthRecoveryChallenge's table name
func (*AuthRecoveryChallenge) TableName() string {
	return TableNameAuthRecoveryChallenge
}
