// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCampus = "campus"

// Campus 校区表
type Campus struct {
	ID             int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                   // 主键ID
	OrganizationID int32     `gorm:"column:organization_id;type:int unsigned;not null;comment:机构ID" json:"organization_id"`              // 机构ID
	CampusCode     string    `gorm:"column:campus_code;type:varchar(50);not null;comment:校区编码" json:"campus_code"`                       // 校区编码
	CampusName     string    `gorm:"column:campus_name;type:varchar(100);not null;comment:校区名称" json:"campus_name"`                      // 校区名称
	Status         string    `gorm:"column:status;type:varchar(20);not null;default:active;comment:状态：active/inactive" json:"status"`    // 状态：active/inactive
	FeatureFlags   *string   `gorm:"column:feature_flags;type:json;comment:校区级功能开关" json:"feature_flags"`                                // 校区级功能开关
	Remark         string    `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`                                  // 备注
	CreatedAt      time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Campus's table name
func (*Campus) TableName() string {
	return TableNameCampus
}
