// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCourse = "course"

// Course 课程定义表
type Course struct {
	ID              int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                   // 主键ID
	OrganizationID  int32     `gorm:"column:organization_id;type:int unsigned;not null;default:1;comment:所属机构ID" json:"organization_id"`  // 所属机构ID
	CampusID        int32     `gorm:"column:campus_id;type:int unsigned;not null;default:1;comment:所属校区ID" json:"campus_id"`              // 所属校区ID
	CourseName      string    `gorm:"column:course_name;type:varchar(100);not null;comment:课程名称" json:"course_name"`                      // 课程名称
	Subject         string    `gorm:"column:subject;type:varchar(50);not null;comment:科目" json:"subject"`                                 // 科目
	CourseType      string    `gorm:"column:course_type;type:varchar(30);not null;comment:课程类型" json:"course_type"`                       // 课程类型
	DurationMinutes int32     `gorm:"column:duration_minutes;type:int;not null;default:60;comment:标准时长，单位分钟" json:"duration_minutes"`     // 标准时长，单位分钟
	FeeStandard     float64   `gorm:"column:fee_standard;type:decimal(10,2);not null;default:0.00;comment:标准收费" json:"fee_standard"`      // 标准收费
	Remark          string    `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`                                  // 备注
	Status          string    `gorm:"column:status;type:varchar(20);not null;default:enabled;comment:状态：enabled/disabled" json:"status"`  // 状态：enabled/disabled
	CreatedAt       time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt       time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
}

// TableName Course's table name
func (*Course) TableName() string {
	return TableNameCourse
}
