// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNameLessonPackage = "lesson_package"

// LessonPackage 课时包表
type LessonPackage struct {
	ID                 int32           `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                           // 主键
	OrganizationID     int32           `gorm:"column:organization_id;type:int unsigned;not null;default:1;comment:所属机构ID" json:"organization_id"`                        // 所属机构ID
	CampusID           int32           `gorm:"column:campus_id;type:int unsigned;not null;default:1;comment:所属校区ID" json:"campus_id"`                                    // 所属校区ID
	StudentID          int32           `gorm:"column:student_id;type:int unsigned;not null;comment:学员ID" json:"student_id"`                                              // 学员ID
	CourseID           int32           `gorm:"column:course_id;type:int unsigned;not null;comment:课程ID" json:"course_id"`                                                // 课程ID
	TotalLessons       decimal.Decimal `gorm:"column:total_lessons;type:decimal(10,2);not null;default:0.00;comment:总课时" json:"total_lessons"`                           // 总课时
	UsedLessons        decimal.Decimal `gorm:"column:used_lessons;type:decimal(10,2);not null;default:0.00;comment:已用课时" json:"used_lessons"`                            // 已用课时
	RemainLessons      decimal.Decimal `gorm:"column:remain_lessons;type:decimal(10,2);not null;default:0.00;comment:剩余课时" json:"remain_lessons"`                        // 剩余课时
	TotalAmount        decimal.Decimal `gorm:"column:total_amount;type:decimal(10,2);not null;default:0.00;comment:总金额" json:"total_amount"`                             // 总金额
	PaidAmount         decimal.Decimal `gorm:"column:paid_amount;type:decimal(10,2);not null;default:0.00;comment:已缴金额" json:"paid_amount"`                              // 已缴金额
	StartDate          *time.Time      `gorm:"column:start_date;type:date;comment:生效日期" json:"start_date"`                                                               // 生效日期
	EndDate            *time.Time      `gorm:"column:end_date;type:date;comment:截止日期" json:"end_date"`                                                                   // 截止日期
	Status             string          `gorm:"column:status;type:varchar(20);not null;default:pending;comment:状态：pending/active/exhausted/expired/closed" json:"status"` // 状态：pending/active/exhausted/expired/closed
	LowLessonThreshold decimal.Decimal `gorm:"column:low_lesson_threshold;type:decimal(10,2);not null;default:3.00;comment:低课时提醒阈值" json:"low_lesson_threshold"`         // 低课时提醒阈值
	Remark             string          `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`                                                        // 备注
	CreatedAt          time.Time       `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                       // 创建时间
	UpdatedAt          time.Time       `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                       // 更新时间
}

// TableName LessonPackage's table name
func (*LessonPackage) TableName() string {
	return TableNameLessonPackage
}
