// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLessonRecord = "lesson_record"

// LessonRecord 上课记录表
type LessonRecord struct {
	ID                int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                   // 主键ID
	OrganizationID    int32     `gorm:"column:organization_id;type:int unsigned;not null;default:1;comment:所属机构ID" json:"organization_id"`                  // 所属机构ID
	CampusID          int32     `gorm:"column:campus_id;type:int unsigned;not null;default:1;comment:所属校区ID" json:"campus_id"`                              // 所属校区ID
	ScheduleID        int32     `gorm:"column:schedule_id;type:int unsigned;not null;comment:排课ID" json:"schedule_id"`                                      // 排课ID
	StudentID         int32     `gorm:"column:student_id;type:int unsigned;not null;comment:学员ID" json:"student_id"`                                        // 学员ID
	TeacherID         int32     `gorm:"column:teacher_id;type:int unsigned;not null;comment:教师ID" json:"teacher_id"`                                        // 教师ID
	AttendanceStatus  string    `gorm:"column:attendance_status;type:varchar(20);not null;comment:出勤状态：present/late/absent/leave" json:"attendance_status"` // 出勤状态：present/late/absent/leave
	LessonContent     *string   `gorm:"column:lesson_content;type:text;comment:上课内容" json:"lesson_content"`                                                 // 上课内容
	Homework          *string   `gorm:"column:homework;type:text;comment:作业" json:"homework"`                                                               // 作业
	Feedback          *string   `gorm:"column:feedback;type:text;comment:反馈" json:"feedback"`                                                               // 反馈
	LessonDeducted    bool      `gorm:"column:lesson_deducted;type:tinyint(1);not null;comment:是否已扣课时：0否1是" json:"lesson_deducted"`                         // 是否已扣课时：0否1是
	DeductLessonCount float64   `gorm:"column:deduct_lesson_count;type:decimal(10,2);not null;default:0.00;comment:本次扣减课时数" json:"deduct_lesson_count"`     // 本次扣减课时数
	RecordedAt        time.Time `gorm:"column:recorded_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:记录时间" json:"recorded_at"`               // 记录时间
	UpdatedAt         time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                 // 更新时间
}

// TableName LessonRecord's table name
func (*LessonRecord) TableName() string {
	return TableNameLessonRecord
}
