// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameNotificationRecord = "notification_record"

// NotificationRecord 通知发送记录表
type NotificationRecord struct {
	ID             uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`
	OrganizationID int32      `gorm:"column:organization_id;type:int unsigned;not null;comment:机构ID，平台级或未知为0" json:"organization_id"`
	Channel        string     `gorm:"column:channel;type:varchar(20);not null;comment:通知通道：email/sms" json:"channel"`
	Scene          string     `gorm:"column:scene;type:varchar(64);not null;comment:通知场景" json:"scene"`
	TemplateCode   string     `gorm:"column:template_code;type:varchar(100);not null;comment:模板编码" json:"template_code"`
	TargetMasked   string     `gorm:"column:target_masked;type:varchar(120);not null;comment:脱敏后的目标地址" json:"target_masked"`
	Provider       string     `gorm:"column:provider;type:varchar(64);not null;comment:通知供应商" json:"provider"`
	Status         string     `gorm:"column:status;type:varchar(20);not null;comment:发送状态：accepted/error" json:"status"`
	ErrorCode      string     `gorm:"column:error_code;type:varchar(64);not null;comment:归一化错误码" json:"error_code"`
	ErrorMessage   string     `gorm:"column:error_message;type:varchar(512);not null;comment:错误信息，不包含敏感目标或验证码" json:"error_message"`
	RequestID      string     `gorm:"column:request_id;type:varchar(128);not null;comment:供应商请求ID或幂等键" json:"request_id"`
	Attempts       int32      `gorm:"column:attempts;type:int unsigned;not null;comment:尝试次数" json:"attempts"`
	SentAt         *time.Time `gorm:"column:sent_at;type:timestamp;comment:发送完成时间" json:"sent_at"`
	CreatedAt      time.Time  `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`
}

// TableName NotificationRecord's table name
func (*NotificationRecord) TableName() string {
	return TableNameNotificationRecord
}
