// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrganization = "organization"

// Organization 机构表
type Organization struct {
	ID                 int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                                                    // 主键ID
	OrgCode            string    `gorm:"column:org_code;type:varchar(50);not null;comment:机构编码" json:"org_code"`                                                                              // 机构编码
	OrgName            string    `gorm:"column:org_name;type:varchar(100);not null;comment:机构名称" json:"org_name"`                                                                             // 机构名称
	Status             string    `gorm:"column:status;type:varchar(20);not null;default:active;comment:状态：active/inactive" json:"status"`                                                     // 状态：active/inactive
	SubscriptionStatus string    `gorm:"column:subscription_status;type:varchar(20);not null;default:active;comment:订阅状态：trial/active/past_due/suspended/expired" json:"subscription_status"` // 订阅状态：trial/active/past_due/suspended/expired
	EditionCode        string    `gorm:"column:edition_code;type:varchar(50);not null;default:standard;comment:版本编码" json:"edition_code"`                                                     // 版本编码
	FeatureFlags       *string   `gorm:"column:feature_flags;type:json;comment:机构级功能开关" json:"feature_flags"`                                                                                 // 机构级功能开关
	Timezone           string    `gorm:"column:timezone;type:varchar(50);not null;default:Asia/Shanghai;comment:机构时区" json:"timezone"`                                                        // 机构时区
	Remark             string    `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`                                                                                   // 备注
	CreatedAt          time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                  // 创建时间
	UpdatedAt          time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                  // 更新时间
}

// TableName Organization's table name
func (*Organization) TableName() string {
	return TableNameOrganization
}
