// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"github.com/shopspring/decimal"
)

const TableNamePaymentRecord = "payment_record"

// PaymentRecord 缴费记录表
type PaymentRecord struct {
	ID              int32           `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                                          // 主键
	OrganizationID  int32           `gorm:"column:organization_id;type:int unsigned;not null;default:1;comment:所属机构ID" json:"organization_id"`                                       // 所属机构ID
	CampusID        int32           `gorm:"column:campus_id;type:int unsigned;not null;default:1;comment:所属校区ID" json:"campus_id"`                                                   // 所属校区ID
	StudentID       int32           `gorm:"column:student_id;type:int unsigned;not null;comment:学员ID" json:"student_id"`                                                             // 学员ID
	LessonPackageID int32           `gorm:"column:lesson_package_id;type:int unsigned;not null;comment:课时包ID" json:"lesson_package_id"`                                              // 课时包ID
	PaymentType     string          `gorm:"column:payment_type;type:varchar(20);not null;default:signup;comment:缴费类型：signup/renewal" json:"payment_type"`                            // 缴费类型：signup/renewal
	Amount          decimal.Decimal `gorm:"column:amount;type:decimal(10,2);not null;default:0.00;comment:缴费金额" json:"amount"`                                                       // 缴费金额
	PaymentMethod   string          `gorm:"column:payment_method;type:varchar(20);not null;default:other;comment:支付方式：cash/wechat/alipay/bank_transfer/other" json:"payment_method"` // 支付方式：cash/wechat/alipay/bank_transfer/other
	PaymentTime     time.Time       `gorm:"column:payment_time;type:datetime;not null;comment:缴费时间" json:"payment_time"`                                                             // 缴费时间
	PaymentStatus   string          `gorm:"column:payment_status;type:varchar(20);not null;default:paid;comment:状态：paid/pending/partial/refunded" json:"payment_status"`             // 状态：paid/pending/partial/refunded
	Remark          string          `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`                                                                       // 备注
	CreatedAt       time.Time       `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                      // 创建时间
	UpdatedAt       time.Time       `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                      // 更新时间
}

// TableName PaymentRecord's table name
func (*PaymentRecord) TableName() string {
	return TableNamePaymentRecord
}
