// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRescheduleRecord = "reschedule_record"

// RescheduleRecord 调补课记录表
type RescheduleRecord struct {
	ID             int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                  // 主键
	OrganizationID int32     `gorm:"column:organization_id;type:int unsigned;not null;default:1;comment:所属机构ID" json:"organization_id"`               // 所属机构ID
	CampusID       int32     `gorm:"column:campus_id;type:int unsigned;not null;default:1;comment:所属校区ID" json:"campus_id"`                           // 所属校区ID
	OldScheduleID  int32     `gorm:"column:old_schedule_id;type:int unsigned;not null;comment:原排课ID" json:"old_schedule_id"`                          // 原排课ID
	NewScheduleID  *int32    `gorm:"column:new_schedule_id;type:int unsigned;comment:新排课ID" json:"new_schedule_id"`                                   // 新排课ID
	OperationType  string    `gorm:"column:operation_type;type:varchar(20);not null;comment:类型：leave/reschedule/makeup/cancel" json:"operation_type"` // 类型：leave/reschedule/makeup/cancel
	Reason         string    `gorm:"column:reason;type:varchar(255);not null;comment:原因" json:"reason"`                                               // 原因
	OperatorID     *int32    `gorm:"column:operator_id;type:int unsigned;comment:操作人" json:"operator_id"`                                             // 操作人
	CreatedAt      time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`              // 创建时间
}

// TableName RescheduleRecord's table name
func (*RescheduleRecord) TableName() string {
	return TableNameRescheduleRecord
}
