// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSchemaMigrations = "schema_migrations"

// SchemaMigrations schema migrations
type SchemaMigrations struct {
	Version        string    `gorm:"column:version;type:varchar(255);primaryKey" json:"version"`
	Checksum       string    `gorm:"column:checksum;type:varchar(64);not null" json:"checksum"`
	RollbackPolicy string    `gorm:"column:rollback_policy;type:varchar(64);not null" json:"rollback_policy"`
	AppliedAt      time.Time `gorm:"column:applied_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"applied_at"`
}

// TableName SchemaMigrations's table name
func (*SchemaMigrations) TableName() string {
	return TableNameSchemaMigrations
}
