// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSchedule = "schedule"

// Schedule 排课表
type Schedule struct {
	ID                 int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                                                                      // 主键
	OrganizationID     int32     `gorm:"column:organization_id;type:int unsigned;not null;default:1;comment:所属机构ID" json:"organization_id"`                                                                   // 所属机构ID
	CampusID           int32     `gorm:"column:campus_id;type:int unsigned;not null;default:1;comment:所属校区ID" json:"campus_id"`                                                                               // 所属校区ID
	StudentID          int32     `gorm:"column:student_id;type:int unsigned;not null;comment:学员ID" json:"student_id"`                                                                                         // 学员ID
	CourseID           int32     `gorm:"column:course_id;type:int unsigned;not null;comment:课程ID" json:"course_id"`                                                                                           // 课程ID
	TeacherID          int32     `gorm:"column:teacher_id;type:int unsigned;not null;comment:教师ID" json:"teacher_id"`                                                                                         // 教师ID
	LessonPackageID    *int32    `gorm:"column:lesson_package_id;type:int unsigned;comment:关联课时包ID" json:"lesson_package_id"`                                                                                 // 关联课时包ID
	ClassDate          time.Time `gorm:"column:class_date;type:date;not null;comment:上课日期" json:"class_date"`                                                                                                 // 上课日期
	StartTime          time.Time `gorm:"column:start_time;type:datetime;not null;comment:开始时间" json:"start_time"`                                                                                             // 开始时间
	EndTime            time.Time `gorm:"column:end_time;type:datetime;not null;comment:结束时间" json:"end_time"`                                                                                                 // 结束时间
	Classroom          string    `gorm:"column:classroom;type:varchar(100);not null;comment:教室/地点" json:"classroom"`                                                                                          // 教室/地点
	ScheduleStatus     string    `gorm:"column:schedule_status;type:varchar(20);not null;default:scheduled;comment:状态：scheduled/completed/leave/rescheduled/cancelled/makeup_pending" json:"schedule_status"` // 状态：scheduled/completed/leave/rescheduled/cancelled/makeup_pending
	OriginalScheduleID *int32    `gorm:"column:original_schedule_id;type:int unsigned;comment:原始课程ID" json:"original_schedule_id"`                                                                            // 原始课程ID
	IsMakeup           bool      `gorm:"column:is_makeup;type:tinyint(1);not null;comment:是否补课：0否1是" json:"is_makeup"`                                                                                        // 是否补课：0否1是
	Remark             string    `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`                                                                                                   // 备注
	CreatedAt          time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                                  // 创建时间
	UpdatedAt          time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                                                  // 更新时间
}

// TableName Schedule's table name
func (*Schedule) TableName() string {
	return TableNameSchedule
}
