// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameStudent = "student"

// Student 学员表
type Student struct {
	ID             int32     `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                                         // 主键
	OrganizationID int32     `gorm:"column:organization_id;type:int unsigned;not null;default:1;comment:所属机构ID" json:"organization_id"`                                      // 所属机构ID
	CampusID       int32     `gorm:"column:campus_id;type:int unsigned;not null;default:1;comment:所属校区ID" json:"campus_id"`                                                  // 所属校区ID
	StudentName    string    `gorm:"column:student_name;type:varchar(50);not null;comment:学员姓名" json:"student_name"`                                                         // 学员姓名
	Gender         string    `gorm:"column:gender;type:varchar(10);not null;default:unknown;comment:性别：male/female/unknown" json:"gender"`                                   // 性别：male/female/unknown
	Grade          string    `gorm:"column:grade;type:varchar(30);not null;comment:年级" json:"grade"`                                                                         // 年级
	Phone          string    `gorm:"column:phone;type:varchar(20);not null;comment:学员手机号" json:"phone"`                                                                      // 学员手机号
	ParentName     string    `gorm:"column:parent_name;type:varchar(50);not null;comment:家长姓名" json:"parent_name"`                                                           // 家长姓名
	ParentPhone    string    `gorm:"column:parent_phone;type:varchar(20);not null;comment:家长电话" json:"parent_phone"`                                                         // 家长电话
	Subject        string    `gorm:"column:subject;type:varchar(50);not null;comment:报读科目" json:"subject"`                                                                   // 报读科目
	TeachingType   string    `gorm:"column:teaching_type;type:varchar(20);not null;default:one_to_one;comment:授课形式：one_to_one/one_to_many/small_class" json:"teaching_type"` // 授课形式：one_to_one/one_to_many/small_class
	Status         string    `gorm:"column:status;type:varchar(20);not null;default:active;comment:状态：active/suspended/graduated" json:"status"`                             // 状态：active/suspended/graduated
	Remark         string    `gorm:"column:remark;type:varchar(500);not null;comment:备注" json:"remark"`                                                                      // 备注
	CreatedAt      time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                     // 创建时间
	UpdatedAt      time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                                     // 更新时间
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
