// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSubscription = "subscription"

// Subscription 机构订阅表
type Subscription struct {
	ID             int32      `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                          // 主键ID
	OrganizationID int32      `gorm:"column:organization_id;type:int unsigned;not null;comment:机构ID" json:"organization_id"`                                     // 机构ID
	PlanCode       string     `gorm:"column:plan_code;type:varchar(50);not null;default:standard;comment:套餐编码" json:"plan_code"`                                 // 套餐编码
	Status         string     `gorm:"column:status;type:varchar(20);not null;default:active;comment:订阅状态：trial/active/past_due/suspended/expired" json:"status"` // 订阅状态：trial/active/past_due/suspended/expired
	StartsAt       *time.Time `gorm:"column:starts_at;type:datetime;comment:生效时间" json:"starts_at"`                                                              // 生效时间
	EndsAt         *time.Time `gorm:"column:ends_at;type:datetime;comment:到期时间" json:"ends_at"`                                                                  // 到期时间
	FeatureFlags   *string    `gorm:"column:feature_flags;type:json;comment:订阅功能开关" json:"feature_flags"`                                                        // 订阅功能开关
	MaxCampuses    int32      `gorm:"column:max_campuses;type:int unsigned;not null;default:1;comment:最大校区数" json:"max_campuses"`                                // 最大校区数
	MaxUsers       int32      `gorm:"column:max_users;type:int unsigned;not null;default:100;comment:最大用户数" json:"max_users"`                                    // 最大用户数
	Remark         string     `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`                                                         // 备注
	FollowUpStatus string     `gorm:"column:follow_up_status;type:varchar(50);not null;comment:续费跟进状态" json:"follow_up_status"`                                  // 续费跟进状态
	FollowUpOwner  string     `gorm:"column:follow_up_owner;type:varchar(100);not null;comment:跟进负责人" json:"follow_up_owner"`                                    // 跟进负责人
	FollowUpNote   string     `gorm:"column:follow_up_note;type:varchar(255);not null;comment:跟进备注" json:"follow_up_note"`                                       // 跟进备注
	LastContactAt  *time.Time `gorm:"column:last_contact_at;type:datetime;comment:最近联系时间" json:"last_contact_at"`                                                // 最近联系时间
	CreatedAt      time.Time  `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                        // 创建时间
	UpdatedAt      time.Time  `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                        // 更新时间
}

// TableName Subscription's table name
func (*Subscription) TableName() string {
	return TableNameSubscription
}
