// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysUser = "sys_user"

// SysUser 系统用户表
type SysUser struct {
	ID                    int32      `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键ID" json:"id"`                                       // 主键ID
	Username              string     `gorm:"column:username;type:varchar(50);not null;comment:登录账号" json:"username"`                                                 // 登录账号
	PasswordHash          string     `gorm:"column:password_hash;type:varchar(255);not null;comment:密码哈希" json:"password_hash"`                                      // 密码哈希
	RoleCode              string     `gorm:"column:role_code;type:varchar(32);not null;comment:角色编码：platform_admin/org_admin/campus_admin/teacher" json:"role_code"` // 角色编码：platform_admin/org_admin/campus_admin/teacher
	OrganizationID        *int32     `gorm:"column:organization_id;type:int unsigned;comment:所属机构ID" json:"organization_id"`                                         // 所属机构ID
	CampusID              *int32     `gorm:"column:campus_id;type:int unsigned;comment:所属校区ID" json:"campus_id"`                                                     // 所属校区ID
	RealName              string     `gorm:"column:real_name;type:varchar(50);not null;comment:真实姓名" json:"real_name"`                                               // 真实姓名
	Phone                 string     `gorm:"column:phone;type:varchar(20);not null;comment:手机号" json:"phone"`                                                        // 手机号
	Email                 string     `gorm:"column:email;type:varchar(120);not null;comment:邮箱地址，用于账户恢复与二次验证" json:"email"`                                          // 邮箱地址，用于账户恢复与二次验证
	Status                string     `gorm:"column:status;type:varchar(20);not null;default:enabled;comment:状态：enabled/disabled/locked" json:"status"`               // 状态：enabled/disabled/locked
	FailedLoginCount      int32      `gorm:"column:failed_login_count;type:int unsigned;not null;comment:连续登录失败次数" json:"failed_login_count"`                        // 连续登录失败次数
	LockedUntil           *time.Time `gorm:"column:locked_until;type:timestamp;comment:锁定截止时间" json:"locked_until"`                                                  // 锁定截止时间
	MustChangePassword    bool       `gorm:"column:must_change_password;type:tinyint(1);not null;default:1;comment:是否首次登录后必须修改密码" json:"must_change_password"`       // 是否首次登录后必须修改密码
	LastPasswordChangedAt *time.Time `gorm:"column:last_password_changed_at;type:timestamp;comment:最近一次主动修改密码时间" json:"last_password_changed_at"`                    // 最近一次主动修改密码时间
	Remark                string     `gorm:"column:remark;type:varchar(255);not null;comment:备注" json:"remark"`                                                      // 备注
	CreatedAt             time.Time  `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                     // 创建时间
	UpdatedAt             time.Time  `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`                     // 更新时间
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
