// Code generated by cmd/handlergen. DO NOT EDIT.

package course

import (
	"edu-schedule-system/internal/pkg/core"
)

func RegisterGeneratedCourseRoutes(h *Handler, r core.RouterGroup) {
	// 新增数据
	r.POST("/course", h.Create())

	// 获取列表数据
	r.GET("/courses", h.List())

	// 根据 ID 获取数据
	r.GET("/course/:id", h.GetByID())

	// 根据 ID 更新数据
	r.PUT("/course/:id", h.UpdateByID())

	// 根据 ID 删除数据
	r.DELETE("/course/:id", h.DeleteByID())
}
