// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	admin2 "edu-schedule-system/internal/api/admin"
	course2 "edu-schedule-system/internal/api/course"
	lesson_package2 "edu-schedule-system/internal/api/lesson_package"
	lesson_record2 "edu-schedule-system/internal/api/lesson_record"
	payment_record2 "edu-schedule-system/internal/api/payment_record"
	reschedule_record2 "edu-schedule-system/internal/api/reschedule_record"
	schedule2 "edu-schedule-system/internal/api/schedule"
	student2 "edu-schedule-system/internal/api/student"
	"edu-schedule-system/internal/repository/mysql"
	"edu-schedule-system/internal/repository/redis"
	"edu-schedule-system/internal/router"
	"edu-schedule-system/internal/service/admin"
	"edu-schedule-system/internal/service/course"
	"edu-schedule-system/internal/service/lesson_package"
	"edu-schedule-system/internal/service/lesson_record"
	"edu-schedule-system/internal/service/payment_record"
	"edu-schedule-system/internal/service/reschedule_record"
	"edu-schedule-system/internal/service/schedule"
	"edu-schedule-system/internal/service/student"
)

// Injectors from wire.go:

// Injectors
func InitializeApp() (*App, func(), error) {
	logger, err := NewLogger()
	if err != nil {
		return nil, nil, err
	}
	v, err := mysql.New()
	if err != nil {
		return nil, nil, err
	}
	repo, err := redis.NewCache()
	if err != nil {
		return nil, nil, err
	}
	service := admin.New(v)
	handler := admin2.New(logger, service)
	studentService := student.New(v)
	studentHandler := student2.New(logger, studentService)
	courseService := course.New(v)
	courseHandler := course2.New(logger, courseService)
	lesson_packageService := lesson_package.New(v)
	lesson_packageHandler := lesson_package2.New(logger, lesson_packageService)
	payment_recordService := payment_record.New(v)
	payment_recordHandler := payment_record2.New(logger, payment_recordService)
	scheduleService := schedule.New(v)
	scheduleHandler := schedule2.New(logger, scheduleService)
	lesson_recordService := lesson_record.New(v)
	lesson_recordHandler := lesson_record2.New(logger, lesson_recordService)
	reschedule_recordService := reschedule_record.New(v)
	reschedule_recordHandler := reschedule_record2.New(logger, reschedule_recordService)
	mux, err := router.NewHTTPMux(logger, v, repo, handler, studentHandler, courseHandler, lesson_packageHandler, payment_recordHandler, scheduleHandler, lesson_recordHandler, reschedule_recordHandler)
	if err != nil {
		return nil, nil, err
	}
	server := NewHTTPServer(mux)
	app := NewApp(server, logger, v, repo)
	return app, func() {
	}, nil
}
